In [1]:
import pandas as pd

In [10]:
PS_plus = pd.read_csv("../data/SCU_phosphoserines.tsv", sep = "\t")
PS_plus["Modified residue_split"] = PS_plus["Modified residue"].str.split("; MOD_RES")
PS_plus

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Modified residue,Modified residue_split
0,CRX,O43186,reviewed,CRX_HUMAN,Cone-rod homeobox protein,CRX CORD2,Homo sapiens (Human),299,NaN,NaN
1,NFATC1,O95644,reviewed,NFAC1_HUMAN,"Nuclear factor of activated T-cells, cytoplasm...",NFATC1 NFAT2 NFATC,Homo sapiens (Human),943,"MOD_RES 233; /note=""Phosphoserine""; /evidence=...","[MOD_RES 233; /note=""Phosphoserine""; /evidence..."
2,FOS,P01100,reviewed,FOS_HUMAN,Protein c-Fos (Cellular oncogene fos) (Fos pro...,FOS G0S7,Homo sapiens (Human),380,"MOD_RES 10; /note=""Phosphotyrosine; by SRC""; /...","[MOD_RES 10; /note=""Phosphotyrosine; by SRC""; ..."
3,VDR,P11473,reviewed,VDR_HUMAN,"Vitamin D3 receptor (VDR) (1,25-dihydroxyvitam...",VDR NR1I1,Homo sapiens (Human),427,NaN,NaN
4,HMGA1,P17096,reviewed,HMGA1_HUMAN,High mobility group protein HMG-I/HMG-Y (HMG-I...,HMGA1 HMGIY,Homo sapiens (Human),107,"MOD_RES 2; /note=""N-acetylserine""; /evidence=""...","[MOD_RES 2; /note=""N-acetylserine""; /evidence=..."
5,NR4A1,P22736,reviewed,NR4A1_HUMAN,Nuclear receptor subfamily 4immunitygroup A me...,NR4A1 GFRP1 HMR NAK1,Homo sapiens (Human),598,"MOD_RES 341; /note=""Phosphoserine; by PKA""; /e...","[MOD_RES 341; /note=""Phosphoserine; by PKA""; /..."
6,GATA2,P23769,reviewed,GATA2_HUMAN,Endothelial transcription factor GATA-2 (GATA-...,GATA2,Homo sapiens (Human),480,"MOD_RES 73; /note=""Phosphoserine""; /evidence=""...","[MOD_RES 73; /note=""Phosphoserine""; /evidence=..."
7,PAX6,P26367,reviewed,PAX6_HUMAN,Paired box protein Pax-6 (Aniridia type II pro...,PAX6 AN2,Homo sapiens (Human),422,NaN,NaN
8,GATA4,P43694,reviewed,GATA4_HUMAN,Transcription factor GATA-4 (GATA-binding fact...,GATA4,Homo sapiens (Human),442,"MOD_RES 300; /note=""N6-methyllysine; by EZH2"";...","[MOD_RES 300; /note=""N6-methyllysine; by EZH2""..."
9,PITX1,P78337,reviewed,PITX1_HUMAN,Pituitary homeobox 1 (Hindlimb-expressed homeo...,PITX1 BFT PTX1,Homo sapiens (Human),314,"MOD_RES 1; /note=""N-acetylmethionine""; /eviden...","[MOD_RES 1; /note=""N-acetylmethionine""; /evide..."
10,HSF1,Q00613,reviewed,HSF1_HUMAN,Heat shock factor protein 1 (HSF 1) (Heat shoc...,HSF1 HSTF1,Homo sapiens (Human),529,"MOD_RES 1; /note=""N-acetylmethionine""; /eviden...","[MOD_RES 1; /note=""N-acetylmethionine""; /evide..."
11,SOX4,Q06945,reviewed,SOX4_HUMAN,Transcription factor SOX-4,SOX4,Homo sapiens (Human),474,"MOD_RES 95; /note=""N6-acetyllysine""; /evidence...","[MOD_RES 95; /note=""N6-acetyllysine""; /evidenc..."
12,E2F4,Q16254,reviewed,E2F4_HUMAN,Transcription factor E2F4 (E2F-4),E2F4,Homo sapiens (Human),413,"MOD_RES 2; /note=""N-acetylalanine""; /evidence=...","[MOD_RES 2; /note=""N-acetylalanine""; /evidence..."
13,ESR2,Q92731,reviewed,ESR2_HUMAN,Estrogen receptor beta (ER-beta) (Nuclear rece...,ESR2 ESTRB NR3A2,Homo sapiens (Human),530,"MOD_RES 87; /note=""Phosphoserine""; /evidence=""...","[MOD_RES 87; /note=""Phosphoserine""; /evidence=..."
14,TBX5,Q99593,reviewed,TBX5_HUMAN,T-box transcription factor TBX5 (T-box protein 5),TBX5,Homo sapiens (Human),518,"MOD_RES 339; /note=""N6-acetyllysine""; /evidenc...","[MOD_RES 339; /note=""N6-acetyllysine""; /eviden..."
15,KLF6,Q99612,reviewed,KLF6_HUMAN,Krueppel-like factor 6 (B-cell-derived protein...,KLF6 BCD1 COPEB CPBP ST12,Homo sapiens (Human),283,NaN,NaN
16,KLF16,Q9BXK1,reviewed,KLF16_HUMAN,Krueppel-like factor 16 (Basic transcription e...,KLF16 BTEB4 NSLP2,Homo sapiens (Human),252,"MOD_RES 99; /note=""Phosphoserine""; /evidence=""...","[MOD_RES 99; /note=""Phosphoserine""; /evidence=..."

In [19]:
PS_plus_split = PS_plus.explode("Modified residue_split")
PS_plus_split = PS_plus_split.dropna(subset = "Modified residue_split")
PS_plus_split = PS_plus_split[PS_plus_split["Modified residue_split"].str.contains("Phosphoserine")]
PS_plus_split["pos"] = PS_plus_split["Modified residue_split"].str.extract(r'(\d+);').astype(int)
PS_plus_relev_cols = PS_plus_split[["From", "Entry", "pos"]]
PS_plus_relev_cols

      From   Entry  pos
1   NFATC1  O95644  233
1   NFATC1  O95644  237
1   NFATC1  O95644  245
1   NFATC1  O95644  269
1   NFATC1  O95644  294
2      FOS  P01100  362
2      FOS  P01100  374
4    HMGA1  P17096    9
4    HMGA1  P17096   36
4    HMGA1  P17096   44
4    HMGA1  P17096   49
4    HMGA1  P17096   99
4    HMGA1  P17096  102
4    HMGA1  P17096  103
5    NR4A1  P22736  341
5    NR4A1  P22736  351
6    GATA2  P23769   73
6    GATA2  P23769  192
9    PITX1  P78337   46
9    PITX1  P78337   48
10    HSF1  Q00613  121
10    HSF1  Q00613  216
10    HSF1  Q00613  230
10    HSF1  Q00613  275
10    HSF1  Q00613  292
10    HSF1  Q00613  303
10    HSF1  Q00613  307
10    HSF1  Q00613  314
10    HSF1  Q00613  319
10    HSF1  Q00613  320
10    HSF1  Q00613  326
10    HSF1  Q00613  344
10    HSF1  Q00613  363
10    HSF1  Q00613  419
10    HSF1  Q00613  444
12    E2F4  Q16254  384
13    ESR2  Q92731   87
13    ESR2  Q92731  105
16   KLF16  Q9BXK1   99

In [20]:
len(set(PS_plus_relev_cols["From"]))

10

In [22]:
set(PS_plus_relev_cols["From"])

{'E2F4',
 'ESR2',
 'FOS',
 'GATA2',
 'HMGA1',
 'HSF1',
 'KLF16',
 'NFATC1',
 'NR4A1',
 'PITX1'}

In [24]:
known_ADs = pd.read_csv("../output/known_ADs_considering_isoforms_and_canonical.csv")
known_ADs

,Gene,Start,End,uniprotID,Matching Isoforms,Canonical Transcript ID,orig_uniprotID,Reference,TileType,ProteinRegionSeq,Notes
0,ABRAXAS1,121,200,Q6UWZ7,[['Q6UWZ7']],ENST00000321945,Q6UWZ7,DelRosso et al.,CR,LQEHFSNQDLVFLLLTPSIITESCSTHRLEHSLYKPQKGLFHRVPL...,NaN
1,AEBP1,1088,1158,Q8IUX7,[['Q8IUX7']],NaN,Q8IUX7,Staller Activity Data,TF,EVVTEFGTEVEPEFGTKVEPEFETQLEPEFETQLEPEFEEEEEEEK...,NaN
2,AHCTF1,1445,1698,Q8WYP5,"[['Q8WYP5'], ['Q8WYP5']]",nan / nan,Q8WYP5 / Q8WYP5,"PMID: 11952839, Soto / transcriptionalactivity...",TF,IRANDNKSMADVLGDGGNSSLTISEGPIVSERRLNQEVALNLKEDH...,NaN
3,AHR,118,126,P35869,[['P35869']],NaN,P35869,"transcriptionalactivity_regions.txt, GSL",TF,LLQALNGFV,NaN
4,AHR,266,268,P35869,[['P35869']],NaN,P35869,"transcriptionalactivity_regions.txt, GSL",TF,FAI,NaN
...,...,...,...,...,...,...,...,...,...,...,...
739,ZSCAN20,262,341,P17040,"[['P17040', 'P17040-3']]",ENST00000361328,P17040,DelRosso et al.,TF,PSNTSEKEQGPEFWGLSLINSGKRSTADYSLDNEPAQALTWRDSRA...,NaN
740,ZXDA,572,699,P98168,"[['P98168'], ['P98168']]",nan / nan,P98168 / P98168 / P98168,"PMID: 17493635, Soto / R4TA_regions.txt / acti...",TF,QDLLAQLEAANSLTPSSELTSQRQNDLSDAEIVSLFSDVPDSTSAA...,NaN
741,ZXDB,576,703,P98169,[['P98169']],NaN,P98169 / P98169,"R4TA_regions.txt / activation_regions.txt, GSL",TF,QDLLAQLEAANSLTPSSELTSQRQNDLSDAEIVSLFSDVPDSTSAA...,NaN
742,ZXDC,579,688,Q2QGD7,"[['Q2QGD7', 'Q2QGD7-2'], ['Q2QGD7', 'Q2QGD7-2']]",nan / nan,Q2QGD7 / Q2QGD7 / Q2QGD7,"PMID: 16600381, Soto / R4TA_regions.txt / acti...",TF,DSPLVLGTAATVLQQGSFSVDDVQTVSAGALGCLVALPMKNLSDDP...,NaN
743,c-Jun/AP-1,238,257,P05412,[['P05412']],NaN,P05412,"Choi 2000 list, GSL",TF,ETPPLSPIDMESQERIKAER,NaN

In [28]:
PS_plus_relev_cols_ad_pos = pd.merge(PS_plus_relev_cols, known_ADs[["Gene", "Start", "End"]], left_on = "From", right_on = "Gene", how = 'left')
PS_plus_relev_cols_ad_pos

      From   Entry  pos    Gene  Start  End
0   NFATC1  O95644  233  NFATC1      1  218
1   NFATC1  O95644  233  NFATC1    703  943
2   NFATC1  O95644  237  NFATC1      1  218
3   NFATC1  O95644  237  NFATC1    703  943
4   NFATC1  O95644  245  NFATC1      1  218
5   NFATC1  O95644  245  NFATC1    703  943
6   NFATC1  O95644  269  NFATC1      1  218
7   NFATC1  O95644  269  NFATC1    703  943
8   NFATC1  O95644  294  NFATC1      1  218
9   NFATC1  O95644  294  NFATC1    703  943
10     FOS  P01100  362     FOS      1   81
11     FOS  P01100  362     FOS    139  159
12     FOS  P01100  362     FOS    209  371
13     FOS  P01100  374     FOS      1   81
14     FOS  P01100  374     FOS    139  159
15     FOS  P01100  374     FOS    209  371
16   HMGA1  P17096    9   HMGA1     91  107
17   HMGA1  P17096   36   HMGA1     91  107
18   HMGA1  P17096   44   HMGA1     91  107
19   HMGA1  P17096   49   HMGA1     91  107
20   HMGA1  P17096   99   HMGA1     91  107
21   HMGA1  P17096  102   HMGA1     91  107
22   HMGA1  P17096  103   HMGA1     91  107
23   NR4A1  P22736  341   NR4A1    587  598
24   NR4A1  P22736  341   NR4A1      1  201
25   NR4A1  P22736  351   NR4A1    587  598
26   NR4A1  P22736  351   NR4A1      1  201
27   GATA2  P23769   73   GATA2      1   70
28   GATA2  P23769   73   GATA2    410  480
29   GATA2  P23769  192   GATA2      1   70
30   GATA2  P23769  192   GATA2    410  480
31   PITX1  P78337   46   PITX1    234  283
32   PITX1  P78337   48   PITX1    234  283
33    HSF1  Q00613  121    HSF1    362  529
34    HSF1  Q00613  216    HSF1    362  529
35    HSF1  Q00613  230    HSF1    362  529
36    HSF1  Q00613  275    HSF1    362  529
37    HSF1  Q00613  292    HSF1    362  529
38    HSF1  Q00613  303    HSF1    362  529
39    HSF1  Q00613  307    HSF1    362  529
40    HSF1  Q00613  314    HSF1    362  529
41    HSF1  Q00613  319    HSF1    362  529
42    HSF1  Q00613  320    HSF1    362  529
43    HSF1  Q00613  326    HSF1    362  529
44    HSF1  Q00613  344    HSF1    362  529
45    HSF1  Q00613  363    HSF1    362  529
46    HSF1  Q00613  419    HSF1    362  529
47    HSF1  Q00613  444    HSF1    362  529
48    E2F4  Q16254  384    E2F4    302  413
49    ESR2  Q92731   87    ESR2      1  148
50    ESR2  Q92731   87    ESR2    304  500
51    ESR2  Q92731  105    ESR2      1  148
52    ESR2  Q92731  105    ESR2    304  500
53   KLF16  Q9BXK1   99   KLF16    209  252

In [29]:
PS_plus_relev_cols_ad_pos[(PS_plus_relev_cols_ad_pos["pos"] < PS_plus_relev_cols_ad_pos["End"]) & (PS_plus_relev_cols_ad_pos["pos"] > PS_plus_relev_cols_ad_pos["Start"]) ]

     From   Entry  pos   Gene  Start  End
12    FOS  P01100  362    FOS    209  371
20  HMGA1  P17096   99  HMGA1     91  107
21  HMGA1  P17096  102  HMGA1     91  107
22  HMGA1  P17096  103  HMGA1     91  107
45   HSF1  Q00613  363   HSF1    362  529
46   HSF1  Q00613  419   HSF1    362  529
47   HSF1  Q00613  444   HSF1    362  529
48   E2F4  Q16254  384   E2F4    302  413
49   ESR2  Q92731   87   ESR2      1  148
51   ESR2  Q92731  105   ESR2      1  148