In [18]:
import pandas as pd
import glob

In [6]:
for gene in pd.read_csv("../data/SFARI_TF_gene_names.tsv", sep = "\t")["Gene Names"].str.split(" ").str[0].drop_duplicates():
    print(gene)

MEIS2
KLF7
CAMTA2
NKX2-2
AR
THRA
ERG
VDR
TCF4
TFE3
NR1D1
YY1
PAX6
OTX1
RORA
MSX2
NR4A2
PITX1
PAX5
KMT2A
MEF2C
EGR3
NFIA
IKZF1
SMAD4
MTF1
NFIX
NCOA1
HIVEP3
TET2
CC2D1A
SRCAP
CASZ1
GLIS1
ESR2
ARX
KLF16
EBF3
ARNT2
TCF7L2
KDM5B
TCF20
MYT1L
TBX22
NFE2L3

Used this query: https://gpf.sfari.org/hg38/load-query/1335a41c-e716-44dd-adab-89f192febf46

To get de novo missense substitution variants in SFARI TFs (printed above) which are present only in probands and not their siblings.

In [7]:
de_novo_vars_all_cols = pd.read_csv("../data/SFARI_TF_de_novo_variants_gpf.tsv", sep="\t")
de_novo_vars = de_novo_vars_all_cols[["CHROM", "POS", "REF", "ALT"]] 
de_novo_vars["CHROM"] = de_novo_vars["CHROM"].str.split("chr").str[1]
de_novo_vars["start"] = de_novo_vars["POS"] - 1
de_novo_vars["af"] = 0
de_novo_vars = de_novo_vars[["CHROM", "start", "POS", "REF", "ALT", "af"]]
de_novo_vars

/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_26001/2890784154.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  de_novo_vars["CHROM"] = de_novo_vars["CHROM"].str.split("chr").str[1]
/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_26001/2890784154.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  de_novo_vars["start"] = de_novo_vars["POS"] - 1
/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_26001/2890784154.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  de_novo_vars["af"] = 0

    CHROM      start        POS REF ALT  af
0       1   61352563   61352564   C   T   0
1       2    1917306    1917307   A   G   0
2       2  156329363  156329364   A   G   0
3       1   61352563   61352564   C   T   0
4       4  105234730  105234731   G   T   0
..    ...        ...        ...  ..  ..  ..
112    18   55228884   55228885   G   A   0
113    18   55228993   55228994   G   A   0
114    21   38445460   38445461   G   C   0
115    22   42213188   42213189   C   T   0
116    22   42214836   42214837   T   C   0

[117 rows x 6 columns]

In [8]:
# Make bed file for enrichment analysis scripts

In [9]:
de_novo_vars.to_csv("../soto_analysis/raw_files/SFARI_TF_de_novo_variants_gpf.bed", header = None, index = 0, sep = "\t")
de_novo_vars

    CHROM      start        POS REF ALT  af
0       1   61352563   61352564   C   T   0
1       2    1917306    1917307   A   G   0
2       2  156329363  156329364   A   G   0
3       1   61352563   61352564   C   T   0
4       4  105234730  105234731   G   T   0
..    ...        ...        ...  ..  ..  ..
112    18   55228884   55228885   G   A   0
113    18   55228993   55228994   G   A   0
114    21   38445460   38445461   G   C   0
115    22   42213188   42213189   C   T   0
116    22   42214836   42214837   T   C   0

[117 rows x 6 columns]

In [12]:
gnomad_vars = pd.read_csv("../soto_analysis/raw_files/gnomad_missense_snps.bed", sep="\t", header=None)
gnomad_vars.columns = ['CHROM', 'start', 'POS', 'REF', 'ALT', 'af']
gnomad_vars

       CHROM      start        POS REF ALT            af
0          2  207081140  207081141   T   C  3.216086e-06
1          2  207081144  207081145   G   C  7.777610e-07
2          2  207081145  207081146   C   G  7.714145e-07
3          2  207081146  207081147   C   T  1.529487e-06
4          2  207081147  207081148   C   T  5.777024e-06
...      ...        ...        ...  ..  ..           ...
107567    19   13094705   13094706   G   A  7.334088e-07
107568    19   13094708   13094709   G   T  1.997268e-06
107569    19   13094710   13094711   A   G  1.250769e-06
107570    19   13094717   13094718   A   G  3.763805e-05
107571    19   13094719   13094720   A   G  6.577476e-06

[107572 rows x 6 columns]

In [16]:
# Is there any overlap between the de novo vars and gnomad?

de_novo_gnomad_overlap = pd.merge(de_novo_vars, gnomad_vars, on = ['CHROM', 'start', 'POS', 'REF', 'ALT'])
display(de_novo_gnomad_overlap)
print(len(de_novo_gnomad_overlap))

   CHROM      start        POS REF ALT  af_x          af_y
0      1   61352563   61352564   C   T     0  3.732323e-06
1      1   61352563   61352564   C   T     0  3.732323e-06
2      9   37033985   37033986   C   G     0  6.850882e-07
3     10  129840881  129840882   C   G     0  1.591090e-06
4     16   30724602   30724603   A   T     0  6.840441e-07
5      4  105275517  105275518   C   T     0  1.429206e-06
6     10  129840881  129840882   C   G     0  1.591090e-06
7     16   30724602   30724603   A   T     0  6.840441e-07
8     16   30738521   30738522   C   T     0  7.264674e-04
9      1  202749125  202749126   C   T     0  4.983461e-06
10     4  105236333  105236334   G   A     0  1.094617e-05
11     4  105243759  105243760   G   C     0  7.146849e-07
12    17   40097201   40097202   T   C     0  1.596740e-06
13    18   55228986   55228987   C   T     0  1.590417e-06
14     4  105275517  105275518   C   T     0  1.429206e-06
15     5  135028999  135029000   G   A     0  1.590457e-06
16    10  129840881  129840882   C   G     0  1.591090e-06
17    16   30724602   30724603   A   T     0  6.840441e-07
18    16   30729115   30729116   G   A     0  2.168539e-05
19    18   51078305   51078306   A   G     0  1.590391e-06
20     X   80024157   80024158   G   A     0  2.739293e-06
21    15   60499913   60499914   C   T     0  4.121632e-06
22     7   50400039   50400040   G   C     0  1.600343e-06
23     1   61352563   61352564   C   T     0  3.732323e-06
24     4  105275517  105275518   C   T     0  1.429206e-06
25     5  135028999  135029000   G   A     0  1.590457e-06
26    10  129840881  129840882   C   G     0  1.591090e-06
27    16   30729115   30729116   G   A     0  2.168539e-05
28     2   24758045   24758046   G   A     0  8.054553e-06
29     4  105237383  105237384   G   A     0  1.672829e-05
30     7   50400129   50400130   G   A     0  1.417718e-06
31    14   64235128   64235129   G   A     0  8.967530e-06
32    16   30721265   30721266   C   T     0  4.771463e-06
33    19   13928013   13928014   C   T     0  1.363519e-05
34    22   42212529   42212530   C   T     0  3.098131e-06
35     1   10654479   10654480   C   T     0  3.180844e-06
36     1  202750672  202750673   A   G     0  1.200604e-06
37     1  202755279  202755280   T   C     0  7.436419e-06
38     1  202774725  202774726   G   A     0  4.960158e-06
39     2    1892044    1892045   C   T     0  1.306944e-05
40     2    1892097    1892098   G   A     0  1.787361e-06
41     4  105241395  105241396   A   T     0  7.150426e-07
42     7   26185582   26185583   A   G     0  1.368517e-06
43    10  113159982  113159983   G   A     0  1.368143e-06
44    10  129958996  129958997   T   C     0  1.629732e-06
45    11  118490146  118490147   C   T     0  4.114871e-06
46    11  118502481  118502482   G   A     0  2.044861e-05
47    12   47846429   47846430   A   G     0  4.941444e-06
48    16   30733778   30733779   C   T     0  4.789357e-06
49    16   30739400   30739401   C   T     0  6.814952e-06
50    15   61229081   61229082   C   T     0  7.204040e-07
51    17    4969326    4969327   T   C     0  6.586140e-06
52    17    4972899    4972900   C   T     0  2.600033e-05
53    18   51078305   51078306   A   G     0  1.590391e-06
54    22   42213188   42213189   C   T     0  1.363028e-05

55

In [23]:
# De novo in ADs
de_novo_variants_domains = glob.glob("../soto_analysis/outputs/mutations/domains_SFARI_TF_de_novo_variants_gpf_snv_classified/*")
domain_dfs = [pd.read_csv(file, sep="\t", header=None) for file in de_novo_variants_domains if sum(1 for line in open(file)) > 0]
domain_df = pd.concat(domain_dfs)
AD_de_novos = domain_df[domain_df[3] == "AD"]
AD_de_novos

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,17,40097201,40097202,AD,NaN,.,-1,ENST00000246672,17,40097201,...,-1,17,40097201,40097202,T,C,0,D,G,No-Syn
0,8,22692853,22692854,AD,NaN,.,-1,ENST00000317216,8,22692853,...,-1,8,22692853,22692854,T,C,0,S,G,No-Syn
3,22,42214836,42214837,AD,NaN,.,-1,ENST00000359486,22,42214836,...,-1,22,42214836,42214837,T,C,0,T,A,No-Syn
0,X,49030201,49030202,AD,NaN,.,-1,ENST00000315869,X,49030201,...,-1,X,49030201,49030202,C,A,0,A,S,No-Syn
0,5,135028999,135029000,AD,NaN,.,-1,ENST00000265340,5,135028999,...,-1,5,135028999,135029000,G,A,0,L,F,No-Syn
1,5,135028999,135029000,AD,NaN,.,-1,ENST00000265340,5,135028999,...,-1,5,135028999,135029000,G,A,0,L,F,No-Syn
1,15,36892299,36892300,AD,NaN,.,-1,ENST00000561208,15,36892299,...,-1,15,36892299,36892300,G,C,0,P,R,No-Syn
1,14,100277466,100277467,AD,NaN,.,1,ENST00000262238,14,100277466,...,1,14,100277466,100277467,G,A,0,R,H,No-Syn
2,14,100277489,100277490,AD,NaN,.,1,ENST00000262238,14,100277489,...,1,14,100277489,100277490,G,A,0,G,R,No-Syn
4,2,1922902,1922903,AD,NaN,.,-1,ENST00000428368,2,1922902,...,-1,2,1922902,1922903,A,G,0,M,T,No-Syn
3,5,88761218,88761219,AD,NaN,.,-1,ENST00000437473,5,88761218,...,-1,5,88761218,88761219,T,A,0,D,V,No-Syn
0,1,41582026,41582027,AD,NaN,.,-1,ENST00000372583,1,41582026,...,-1,1,41582026,41582027,G,T,0,S,Y,No-Syn
1,10,113159982,113159983,AD,NaN,.,1,ENST00000355995,10,113159982,...,1,10,113159982,113159983,G,A,0,G,D,No-Syn
0,7,50400039,50400040,AD,NaN,.,1,ENST00000331340,7,50400039,...,1,7,50400039,50400040,G,C,0,E,Q,No-Syn
1,7,50400129,50400130,AD,NaN,.,1,ENST00000331340,7,50400129,...,1,7,50400129,50400130,G,A,0,A,T,No-Syn
1,1,202731925,202731926,AD,NaN,.,-1,ENST00000367265,1,202731925,...,-1,1,202731925,202731926,G,A,0,P,L,No-Syn
7,4,105275517,105275518,AD,NaN,.,1,ENST00000380013,4,105275517,...,1,4,105275517,105275518,C,T,0,L,F,No-Syn
8,4,105275517,105275518,AD,NaN,.,1,ENST00000380013,4,105275517,...,1,4,105275517,105275518,C,T,0,L,F,No-Syn
9,4,105275517,105275518,AD,NaN,.,1,ENST00000380013,4,105275517,...,1,4,105275517,105275518,C,T,0,L,F,No-Syn
0,2,24758045,24758046,AD,NaN,.,1,ENST00000348332,2,24758045,...,1,2,24758045,24758046,G,A,0,V,I,No-Syn
0,16,30738427,30738428,AD,NaN,.,1,ENST00000262518,16,30738427,...,1,16,30738427,30738428,G,A,0,M,I,No-Syn
1,16,30738521,30738522,AD,NaN,.,1,ENST00000262518,16,30738521,...,1,16,30738521,30738522,C,T,0,R,C,No-Syn
2,16,30739014,30739015,AD,NaN,.,1,ENST00000262518,16,30739014,...,1,16,30739014,30739015,C,T,0,T,I,No-Syn
3,16,30739023,30739024,AD,NaN,.,1,ENST00000262518,16,30739023,...,1,16,30739023,30739024,C,G,0,T,S,No-Syn
4,16,30739400,30739401,AD,NaN,.,1,ENST00000262518,16,30739400,...,1,16,30739400,30739401,C,T,0,R,W,No-Syn
5,16,30721265,30721266,AD,NaN,.,1,ENST00000262518,16,30721265,...,1,16,30721265,30721266,C,T,0,P,S,No-Syn
0,18,51078305,51078306,AD,NaN,.,1,ENST00000342988,18,51078305,...,1,18,51078305,51078306,A,G,0,I,V,No-Syn
1,18,51078305,51078306,AD,NaN,.,1,ENST00000342988,18,51078305,...,1,18,51078305,51078306,A,G,0,I,V,No-Syn
0,14,64282801,64282802,AD,NaN,.,-1,ENST00000341099,14,64282801,...,-1,14,64282801,64282802,C,T,0,V,I,No-Syn
1,14,64235128,64235129,AD,NaN,.,-1,ENST00000341099,14,64235128,...,-1,14,64235128,64235129,G,A,0,A,V,No-Syn

In [28]:
AD_de_novos = AD_de_novos.rename(columns = {0: 'CHROM', 1: 'start', 2: 'POS', 16: 'REF', 17: 'ALT'})
AD_de_novos[['CHROM', 'start', 'POS', 'REF', 'ALT']]

  CHROM      start        POS REF ALT
0    17   40097201   40097202   T   C
0     8   22692853   22692854   T   C
3    22   42214836   42214837   T   C
0     X   49030201   49030202   C   A
0     5  135028999  135029000   G   A
1     5  135028999  135029000   G   A
1    15   36892299   36892300   G   C
1    14  100277466  100277467   G   A
2    14  100277489  100277490   G   A
4     2    1922902    1922903   A   G
3     5   88761218   88761219   T   A
0     1   41582026   41582027   G   T
1    10  113159982  113159983   G   A
0     7   50400039   50400040   G   C
1     7   50400129   50400130   G   A
1     1  202731925  202731926   G   A
7     4  105275517  105275518   C   T
8     4  105275517  105275518   C   T
9     4  105275517  105275518   C   T
0     2   24758045   24758046   G   A
0    16   30738427   30738428   G   A
1    16   30738521   30738522   C   T
2    16   30739014   30739015   C   T
3    16   30739023   30739024   C   G
4    16   30739400   30739401   C   T
5    16   30721265   30721266   C   T
0    18   51078305   51078306   A   G
1    18   51078305   51078306   A   G
0    14   64282801   64282802   C   T
1    14   64235128   64235129   G   A

In [36]:
gnomad_vars[['CHROM', 'start', 'POS', 'REF', 'ALT']]

       CHROM      start        POS REF ALT
0          2  207081140  207081141   T   C
1          2  207081144  207081145   G   C
2          2  207081145  207081146   C   G
3          2  207081146  207081147   C   T
4          2  207081147  207081148   C   T
...      ...        ...        ...  ..  ..
107567    19   13094705   13094706   G   A
107568    19   13094708   13094709   G   T
107569    19   13094710   13094711   A   G
107570    19   13094717   13094718   A   G
107571    19   13094719   13094720   A   G

[107572 rows x 5 columns]

In [ ]:
# None of 30 AD variants in SFARI TFs overlaps a gnomad variant
pd.merge(AD_de_novos, gnomad_vars, on = ['CHROM', 'start', 'POS', 'REF', 'ALT'])

Empty DataFrame
Columns: [CHROM, start, POS, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, REF, ALT, 18, 19, 20, 21, af]
Index: []

[0 rows x 23 columns]

In [ ]:
# One of 34 DBD variants in SFARI TFs overlaps a gnomad variant
DBD_de_novos = domain_df[domain_df[3] == "DBD"]
DBD_de_novos = DBD_de_novos.rename(columns = {0: 'CHROM', 1: 'start', 2: 'POS', 16: 'REF', 17: 'ALT'})
pd.merge(DBD_de_novos, gnomad_vars, on = ['CHROM', 'start', 'POS', 'REF', 'ALT'])

,CHROM,start,POS,3,4,5,6,7,8,9,...,13,14,15,REF,ALT,18,19,20,21,af
0,X,80024157,80024158,DBD,NaN,.,1,ENST00000373294,X,80024157,...,X,80024157,80024158,G,A,0,R,H,No-Syn,0.000003

# Attempt 1 below

In [19]:
de_novo_vars["effect details"].iloc[0]

'NM_001134673_1:NFIA:missense:272/509(Thr->Met)|NM_005595_1:NFIA:missense:272/498(Thr->Met)|NM_001145511_1:NFIA:missense:264/501(Thr->Met)|NM_001145512_1:NFIA:missense:317/554(Thr->Met)'

In [20]:
de_novo_vars["effect details"] = de_novo_vars["effect details"].str.split("|")
de_novo_vars["effect details"].iloc[0]

/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_4470/610310764.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  de_novo_vars["effect details"] = de_novo_vars["effect details"].str.split("|")

['NM_001134673_1:NFIA:missense:272/509(Thr->Met)',
 'NM_005595_1:NFIA:missense:272/498(Thr->Met)',
 'NM_001145511_1:NFIA:missense:264/501(Thr->Met)',
 'NM_001145512_1:NFIA:missense:317/554(Thr->Met)']

In [ ]:
de_novo_vars_expanded = de_novo_vars.explode("effect details")
de_novo_vars_expanded["full len"] = de_novo_vars_expanded["effect details"].str.extract(r"\/(.*)\(")
de_novo_vars_expanded[de_novo_vars_expanded.isna().any(axis=1)]

,CHROM,POS,REF,ALT,effect details,genes,full len
4,chr4,105234731,G,T,NR_126420_1:TET2-AS1:non-coding-intron:None/No...,TET2,NaN
5,chr9,37033986,C,G,NM_001280551_1:PAX5:5'UTR:113,PAX5,NaN
5,chr9,37033986,C,G,NM_001280556_1:PAX5:5'UTR:113,PAX5,NaN
5,chr9,37033986,C,G,NR_103999_1:PAX5:non-coding:None,PAX5,NaN
5,chr9,37033986,C,G,NR_104000_1:PAX5:non-coding:None,PAX5,NaN
8,chr4,105275518,C,T,NR_126420_1:TET2-AS1:non-coding-intron:None/No...,TET2,NaN
14,chr4,105236334,G,A,NR_126420_1:TET2-AS1:non-coding-intron:None/No...,TET2,NaN
15,chr4,105243760,G,C,NR_126420_1:TET2-AS1:non-coding-intron:None/No...,TET2,NaN
17,chr15,36950345,G,A,NR_051953_1:MEIS2:non-coding-intron:None/None[...,MEIS2,NaN
25,chr4,105275518,C,T,NR_126420_1:TET2-AS1:non-coding-intron:None/No...,TET2,NaN
35,chr15,60499914,C,T,NR_120339_1:RORA-AS1:non-coding-intron:None/No...,RORA,NaN
35,chr15,60499914,C,T,NR_120340_1:RORA-AS1:non-coding-intron:None/No...,RORA,NaN
35,chr15,60499914,C,T,NR_120341_1:RORA-AS1:non-coding-intron:None/No...,RORA,NaN
35,chr15,60499914,C,T,NR_120342_1:RORA-AS1:non-coding-intron:None/No...,RORA,NaN
47,chr4,105275518,C,T,NR_126420_1:TET2-AS1:non-coding-intron:None/No...,TET2,NaN
54,chr2,207123907,G,T,NM_001270942_1:KLF7:intron:3/4[68],KLF7,NaN
54,chr2,207123907,G,T,NR_073108_1:KLF7:non-coding-intron:None/None[N...,KLF7,NaN
55,chr4,105237384,G,A,NM_001127208_1:TET2:intron:3/10[32],TET2,NaN
55,chr4,105237384,G,A,NR_126420_1:TET2-AS1:non-coding-intron:None/No...,TET2,NaN
59,chr14,64235129,G,A,NR_073497_1:ESR2:non-coding:None,ESR2,NaN
59,chr14,64235129,G,A,NR_073496_1:ESR2:non-coding:None,ESR2,NaN
60,chr14,64282802,C,T,NR_073497_1:ESR2:non-coding:None,ESR2,NaN
60,chr14,64282802,C,T,NR_073496_1:ESR2:non-coding:None,ESR2,NaN
66,chrX,67685997,T,C,NM_000044_1:AR:intron:2/7[12],AR,NaN
66,chrX,67685997,T,C,NM_001011645_1:AR:intron:3/8[12],AR,NaN
66,chrX,67685997,T,C,NM_001348061_1:AR:intron:2/3[12],AR,NaN
66,chrX,67685997,T,C,NM_001348063_1:AR:intron:2/3[12],AR,NaN
80,chr2,207124083,G,C,NR_073108_1:KLF7:non-coding-intron:None/None[N...,KLF7,NaN
81,chr4,105241396,A,T,NM_017628_1:TET2:3'UTR:3956,TET2,NaN
81,chr4,105241396,A,T,NR_126420_1:TET2-AS1:non-coding-intron:None/No...,TET2,NaN
82,chr5,88761219,T,A,NM_001131005_1:MEF2C:intron:4/10[93],MEF2C,NaN
82,chr5,88761219,T,A,NM_001193347_1:MEF2C:intron:5/11[49],MEF2C,NaN
82,chr5,88761219,T,A,NM_001193348_1:MEF2C:intron:2/7[9175],MEF2C,NaN
82,chr5,88761219,T,A,NM_001193349_1:MEF2C:intron:2/8[9175],MEF2C,NaN
88,chr10,113159983,G,A,NM_001146274_1:TCF7L2:intron:12/13[635],TCF7L2,NaN
88,chr10,113159983,G,A,NM_001146283_1:TCF7L2:intron:12/12[1913],TCF7L2,NaN
88,chr10,113159983,G,A,NM_001146284_1:TCF7L2:intron:12/12[1265],TCF7L2,NaN
88,chr10,113159983,G,A,NM_001146286_1:TCF7L2:intron:11/11[1913],TCF7L2,NaN
88,chr10,113159983,G,A,NM_001198526_1:TCF7L2:intron:11/12[635],TCF7L2,NaN
88,chr10,113159983,G,A,NM_001198529_1:TCF7L2:intron:12/12[1265],TCF7L2,NaN
88,chr10,113159983,G,A,NM_001198530_1:TCF7L2:intron:10/10[1913],TCF7L2,NaN
88,chr10,113159983,G,A,NM_001198531_1:TCF7L2:intron:12/12[1913],TCF7L2,NaN
99,chr15,36892300,G,C,NM_002399_1:MEIS2:3'UTR:197,MEIS2,NaN
99,chr15,36892300,G,C,NM_170674_1:MEIS2:3'UTR:197,MEIS2,NaN
99,chr15,36892300,G,C,NM_170677_1:MEIS2:3'UTR:197,MEIS2,NaN
99,chr15,36892300,G,C,NR_051953_1:MEIS2:non-coding:None,MEIS2,NaN
99,chr15,36892300,G,C,NM_172315_1:MEIS2:3'UTR:197,MEIS2,NaN
99,chr15,36892300,G,C,NM_172316_1:MEIS2:3'UTR:197,MEIS2,NaN
114,chr21,38445461,G,C,NM_001136155_1:ERG:5'UTR-intron:1/8[21899],ERG,NaN
114,chr21,38445461,G,C,NM_001243429_1:ERG:5'UTR-intron:2/8[21899],ERG,NaN

In [30]:
de_novo_coding_vars_expanded = de_novo_vars_expanded.dropna()
de_novo_coding_vars_expanded

,CHROM,POS,REF,ALT,effect details,genes,full len
0,chr1,61352564,C,T,NM_001134673_1:NFIA:missense:272/509(Thr->Met),NFIA,509
0,chr1,61352564,C,T,NM_005595_1:NFIA:missense:272/498(Thr->Met),NFIA,498
0,chr1,61352564,C,T,NM_001145511_1:NFIA:missense:264/501(Thr->Met),NFIA,501
0,chr1,61352564,C,T,NM_001145512_1:NFIA:missense:317/554(Thr->Met),NFIA,554
1,chr2,1917307,A,G,NM_001303052_1:MYT1L:missense:506/1186(Cys->Arg),MYT1L,1186
...,...,...,...,...,...,...,...
114,chr21,38445461,G,C,NM_001291391_1:ERG:missense:67/325(Pro->Arg),ERG,325
115,chr22,42213189,C,T,NM_005650_3:TCF20:missense:706/1960(Arg->His),TCF20,1960
115,chr22,42213189,C,T,NM_181492_1:TCF20:missense:706/1938(Arg->His),TCF20,1938
116,chr22,42214837,T,C,NM_005650_3:TCF20:missense:157/1960(Thr->Ala),TCF20,1960
116,chr22,42214837,T,C,NM_181492_1:TCF20:missense:157/1938(Thr->Ala),TCF20,1938

In [31]:
de_novo_coding_vars_expanded["full len"] = de_novo_coding_vars_expanded["full len"].str.strip()
de_novo_coding_vars_expanded["full len"] = de_novo_coding_vars_expanded["full len"].astype(int)
de_novo_coding_vars_expanded

/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_4470/2648747921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  de_novo_coding_vars_expanded["full len"] = de_novo_coding_vars_expanded["full len"].str.strip()
/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_4470/2648747921.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  de_novo_coding_vars_expanded["full len"] = de_novo_coding_vars_expanded["full len"].astype(int)

,CHROM,POS,REF,ALT,effect details,genes,full len
0,chr1,61352564,C,T,NM_001134673_1:NFIA:missense:272/509(Thr->Met),NFIA,509
0,chr1,61352564,C,T,NM_005595_1:NFIA:missense:272/498(Thr->Met),NFIA,498
0,chr1,61352564,C,T,NM_001145511_1:NFIA:missense:264/501(Thr->Met),NFIA,501
0,chr1,61352564,C,T,NM_001145512_1:NFIA:missense:317/554(Thr->Met),NFIA,554
1,chr2,1917307,A,G,NM_001303052_1:MYT1L:missense:506/1186(Cys->Arg),MYT1L,1186
...,...,...,...,...,...,...,...
114,chr21,38445461,G,C,NM_001291391_1:ERG:missense:67/325(Pro->Arg),ERG,325
115,chr22,42213189,C,T,NM_005650_3:TCF20:missense:706/1960(Arg->His),TCF20,1960
115,chr22,42213189,C,T,NM_181492_1:TCF20:missense:706/1938(Arg->His),TCF20,1938
116,chr22,42214837,T,C,NM_005650_3:TCF20:missense:157/1960(Thr->Ala),TCF20,1960
116,chr22,42214837,T,C,NM_181492_1:TCF20:missense:157/1938(Thr->Ala),TCF20,1938

In [34]:
de_novo_coding_vars_expanded[["CHROM", "POS", "REF", "ALT"]].drop_duplicates()

     CHROM        POS REF ALT
0     chr1   61352564   C   T
1     chr2    1917307   A   G
2     chr2  156329364   A   G
4     chr4  105234731   G   T
5     chr9   37033986   C   G
..     ...        ...  ..  ..
112  chr18   55228885   G   A
113  chr18   55228994   G   A
114  chr21   38445461   G   C
115  chr22   42213189   C   T
116  chr22   42214837   T   C

[97 rows x 4 columns]