In [1]:
import pandas as pd
import metapredict

# 1. Get IDR intervals

In [3]:
# Reading in all TF sequences
TF_seqs = pd.read_csv("../output/lambert_TFs_10-21-24_with_DBD_coords.csv", index_col = 0)
TF_seqs

,id,ProteinSeq,DBD_coords_merged
0,sp|A0A087WUV0|ZN892_HUMAN Zinc finger protein ...,MEPEGRGSLFEDSDLLHAGNPKENDVTAVLLTPGSQELMIRDMAEA...,"[[221, 243], [249, 271], [277, 299], [305, 327..."
1,sp|A0AVK6|E2F8_HUMAN Transcription factor E2F8...,MENEKENLFCEPHKRGLMKTPLKESTTANIVLAEIQPDFGPLTTPT...,"[[114, 182], [262, 347]]"
2,sp|A0PJY2|FEZF1_HUMAN Fez family zinc finger p...,MDSSCHNATTKMLATAPARGNMMSTSKPLAFSIERIMARTPEPKAL...,"[[260, 282], [288, 310], [316, 338], [344, 366..."
3,sp|A1A519|F170A_HUMAN Protein FAM170A OS=Homo ...,MKRRQKRKHLENEESQETAEKGGGMSKSQEDALQPGSTRVAKGWSQ...,"[[1, 330]]"
4,sp|A1YPR0|ZBT7C_HUMAN Zinc finger and BTB doma...,MANDIDELIGIPFPNHSSEVLCSLNEQRHDGLLCDVLLVVQEQEYR...,"[[364, 386], [392, 414], [420, 442], [448, 469]]"
...,...,...,...
1608,sp|Q9Y6Q9|NCOA3_HUMAN Nuclear receptor coactiv...,MSGLGENLDPLASDSRKRKLPCDTPGQGLTCSGEKRRREQESKYIE...,"[[31, 83]]"
1609,sp|Q9Y6R6|Z780B_HUMAN Zinc finger protein 780B...,MVHGSVTFRDVAIDFSQEEWECLQPDQRTLYRDVMLENYSHLISLG...,"[[165, 187], [193, 215], [221, 243], [249, 271..."
1610,sp|Q9Y6X0|SETBP_HUMAN SET-binding protein OS=H...,MESRETLSSSRQRGGESDFLPVSSAKPPAAPGCAGEPLLSTPGPGK...,"[[583, 596], [1015, 1027], [1450, 1462]]"
1611,sp|Q9Y6X8|ZHX2_HUMAN Zinc fingers and homeobox...,MASKRKSTTPCMVRTSQVVEQDVPEEVDRAKEKGIGTPQPDVAKDS...,"[[78, 101], [110, 133], [271, 317], [442, 496]..."
1612,sp|Q9Y6Y1|CMTA1_HUMAN Calmodulin-binding trans...,MWRAEGKWLPKTSRKSVSQSVFCGTSTYCVLNTVPPIEDDHGNSNS...,"[[69, 182]]"

In [92]:
# Running metapredict on each sequence to get IDR intervals
from concurrent.futures import ThreadPoolExecutor
from tqdm import tqdm

def process_sequence(seq):
    output = [[start + 1, end + 1] for start, end in metapredict.predict_disorder_domains(seq).disordered_domain_boundaries]
    return "NA-NA" if len(output) == 0 else str(output)

results = []
with ThreadPoolExecutor() as executor:
    for res in tqdm(executor.map(process_sequence, TF_seqs["ProteinSeq"]), total=len(TF_seqs)):
        results.append(res)

TF_seqs["IDR_coords_merged"] = results

100%|██████████| 1613/1613 [00:07<00:00, 212.77it/s]

In [93]:
TF_seqs["uniprotID"] = TF_seqs["id"].str.split("|").str[1]
TF_seqs

,id,ProteinSeq,DBD_coords_merged,IDR_coords_merged,uniprotID,IDR_coords
0,sp|A0A087WUV0|ZN892_HUMAN Zinc finger protein ...,MEPEGRGSLFEDSDLLHAGNPKENDVTAVLLTPGSQELMIRDMAEA...,"[[221, 243], [249, 271], [277, 299], [305, 327...","[[1, 216], [498, 523]]",A0A087WUV0,"1-216,498-523"
1,sp|A0AVK6|E2F8_HUMAN Transcription factor E2F8...,MENEKENLFCEPHKRGLMKTPLKESTTANIVLAEIQPDFGPLTTPT...,"[[114, 182], [262, 347]]","[[1, 115], [337, 868]]",A0AVK6,"1-115,337-868"
2,sp|A0PJY2|FEZF1_HUMAN Fez family zinc finger p...,MDSSCHNATTKMLATAPARGNMMSTSKPLAFSIERIMARTPEPKAL...,"[[260, 282], [288, 310], [316, 338], [344, 366...","[[1, 220], [422, 476]]",A0PJY2,"1-220,422-476"
3,sp|A1A519|F170A_HUMAN Protein FAM170A OS=Homo ...,MKRRQKRKHLENEESQETAEKGGGMSKSQEDALQPGSTRVAKGWSQ...,"[[1, 330]]","[[1, 219], [269, 331]]",A1A519,"1-219,269-331"
4,sp|A1YPR0|ZBT7C_HUMAN Zinc finger and BTB doma...,MANDIDELIGIPFPNHSSEVLCSLNEQRHDGLLCDVLLVVQEQEYR...,"[[364, 386], [392, 414], [420, 442], [448, 469]]","[[128, 364], [471, 620]]",A1YPR0,"128-364,471-620"
...,...,...,...,...,...,...
1608,sp|Q9Y6Q9|NCOA3_HUMAN Nuclear receptor coactiv...,MSGLGENLDPLASDSRKRKLPCDTPGQGLTCSGEKRRREQESKYIE...,"[[31, 83]]","[[1, 40], [86, 108], [177, 193], [355, 1425]]",Q9Y6Q9,"1-40,86-108,177-193,355-1425"
1609,sp|Q9Y6R6|Z780B_HUMAN Zinc finger protein 780B...,MVHGSVTFRDVAIDFSQEEWECLQPDQRTLYRDVMLENYSHLISLG...,"[[165, 187], [193, 215], [221, 243], [249, 271...","[[64, 161], [809, 834]]",Q9Y6R6,"64-161,809-834"
1610,sp|Q9Y6X0|SETBP_HUMAN SET-binding protein OS=H...,MESRETLSSSRQRGGESDFLPVSSAKPPAAPGCAGEPLLSTPGPGK...,"[[583, 596], [1015, 1027], [1450, 1462]]","[[1, 1400], [1437, 1597]]",Q9Y6X0,"1-1400,1437-1597"
1611,sp|Q9Y6X8|ZHX2_HUMAN Zinc fingers and homeobox...,MASKRKSTTPCMVRTSQVVEQDVPEEVDRAKEKGIGTPQPDVAKDS...,"[[78, 101], [110, 133], [271, 317], [442, 496]...","[[1, 76], [150, 283], [334, 447], [589, 640], ...",Q9Y6X8,"1-76,150-283,334-447,589-640,695-838"
1612,sp|Q9Y6Y1|CMTA1_HUMAN Calmodulin-binding trans...,MWRAEGKWLPKTSRKSVSQSVFCGTSTYCVLNTVPPIEDDHGNSNS...,"[[69, 182]]","[[1, 55], [245, 863], [993, 1035], [1171, 1515...",Q9Y6Y1,"1-55,245-863,993-1035,1171-1515,1644-1674"

In [94]:
all_TFs_table = pd.read_csv("../soto_analysis/outputs/all_TFs_table_proteins.txt", sep = "\t", index_col = 0)
all_TFs_table

,1,2,uniprotID,ENSG,ENST,DBD_coords,AD_coords,RD_coords,Bif_coords,length
0,NaN,NaN,A0A087WUV0,NaN,ENST00000425953,"221-243,249-271,277-299,305-327,333-355,361-38...",NaN,NaN,NaN,1
1,NaN,NaN,A0AVK6,NaN,ENST00000250024,"114-182,262-347",NaN,NaN,NaN,1
2,NaN,NaN,A1YPR0,NaN,ENST00000535628,"364-386,392-414,420-442,448-469",NaN,NaN,NaN,1
3,NaN,NaN,A2RRD8,NaN,ENST00000391781,"161-183,189-211,217-239,245-267,273-295,301-32...",NaN,NaN,NaN,1
4,NaN,NaN,A2RU54,NaN,ENST00000339992,150-206,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...
1585,NaN,NaN,Q9Y692,NaN,ENST00000294409,89-165,422-573,NaN,NaN,1
1586,NaN,NaN,Q9Y6Q3,NaN,ENST00000374227,"293-315,321-343,377-399,405-427,433-455,461-48...",NaN,NaN,NaN,1
1587,NaN,NaN,Q9Y6Q9,NaN,ENST00000371998,31-83,621-1424,NaN,NaN,1
1588,NaN,NaN,Q9Y6X0,NaN,ENST00000649279,"583-596,1015-1027,1450-1462",NaN,NaN,NaN,1
1589,NaN,NaN,Q9Y6Y1,NaN,ENST00000303635,69-182,"702-841,422-501",NaN,NaN,1

In [100]:
# Converting the output from metapredict to output necessary for Soto script
import ast

def convert_ranges_from_string(input_string):
    # Convert the string to a list of lists
    input_list = ast.literal_eval(input_string)
    
    # Convert the list of lists into the desired string format
    return ','.join([f"{start}-{end}" for start, end in input_list])

IDR_coords = []
for i in TF_seqs["IDR_coords_merged"]:
    print(i)
    if i == "NA-NA":
        IDR_coords.append("NA-NA")
    else:
        IDR_coords.append(convert_ranges_from_string(i))

TF_seqs["IDR_coords"] = IDR_coords
TF_seqs

[[1, 216], [498, 523]]
[[1, 115], [337, 868]]
[[1, 220], [422, 476]]
[[1, 219], [269, 331]]
[[128, 364], [471, 620]]
[[51, 156]]
[[1, 158], [224, 274]]
[[1, 56], [126, 1350]]
[[1, 138], [194, 302]]
[[1, 14], [131, 243]]
[[1, 162], [206, 345], [501, 690], [932, 1005]]
[[1, 20], [79, 110], [173, 192]]
[[1, 48], [123, 352], [472, 497]]
[[1, 249], [579, 633]]
[[1, 235], [308, 358]]
[[1, 125]]
[[1, 144], [195, 266]]
[[1, 83], [137, 208], [266, 316]]
[[1, 57], [142, 351]]
[[1, 109], [161, 532]]
[[63, 450], [658, 671]]
[[70, 180], [544, 573]]
[[1, 95], [221, 413]]
[[74, 100], [162, 205]]
[[1, 18], [72, 149], [367, 417]]
[[1, 187], [241, 344]]
[[70, 242], [1208, 1253]]
[[1, 30], [90, 264]]
[[65, 173]]
[[1, 14], [67, 212], [482, 496]]
[[1, 32], [85, 168], [373, 406]]
[[55, 195]]
[[1, 21], [84, 319]]
NA-NA
[[1, 133], [234, 421]]
[[1, 109], [221, 252]]
[[60, 170]]
[[63, 166], [470, 500]]
[[67, 167]]
[[58, 231]]
[[1, 86], [159, 493]]
[[68, 143]]
[[1, 28], [93, 278], [373, 449]]
[[1, 23], [120, 292]]
[[1, 17], [69, 198], [551, 564]]
[[67, 146]]
[[65, 189]]
[[1, 241]]
[[1, 102], [170, 256], [314, 422], [487, 586], [655, 679]]
[[48, 134]]
[[1, 14], [58, 239], [371, 403]]
[[192, 380]]
[[1, 71]]
[[1, 239], [319, 343]]
[[1, 63], [213, 279], [450, 627]]
[[1, 53], [146, 374]]
[[1, 112], [210, 491]]
[[1, 72], [187, 278], [336, 391]]
[[1, 79], [203, 299]]
[[1, 57], [128, 392]]
[[187, 421]]
[[1, 180], [341, 466]]
[[1, 44], [183, 413]]
[[103, 175], [274, 298], [379, 555], [633, 879], [959, 1045], [1134, 1177], [1226, 1487]]
[[135, 583]]
[[1, 160], [237, 285]]
[[65, 240], [330, 409]]
[[1, 43], [131, 372], [1014, 1030]]
[[1, 119], [255, 268]]
[[1, 76], [190, 282], [342, 478]]
[[1, 47], [113, 318]]
[[1, 86], [150, 285]]
[[1, 15], [134, 533], [640, 737]]
[[116, 211], [448, 468]]
[[1, 420], [481, 513]]
[[1, 130], [233, 348]]
[[1, 47], [129, 434], [541, 572], [665, 684]]
[[1, 272], [355, 1412]]
[[1, 242], [310, 375], [418, 463], [519, 615], [664, 1051], [1100, 1208], [1275, 1545], [1605, 1678], [1774, 1833]]
[[1, 30], [121, 346], [562, 602]]
[[146, 601]]
[[1, 134], [213, 272], [325, 344], [395, 751], [801, 1301]]
[[1, 100], [306, 744]]
[[1, 344], [456, 540]]
[[1, 93]]
[[1, 15], [227, 436]]
[[1, 21], [145, 253]]
[[1, 35], [151, 484], [563, 635]]
[[1, 165], [414, 443], [518, 591], [678, 691]]
[[1, 122], [187, 293]]
[[1, 122], [305, 490], [601, 637]]
[[1, 272], [372, 649]]
[[1, 39], [107, 316]]
[[1, 253]]
[[1, 111], [162, 347], [410, 491], [585, 716]]
[[1, 130], [186, 206]]
[[1, 52], [390, 519], [559, 847]]
[[1, 88], [143, 240]]
[[1, 28], [120, 163]]
[[1, 14], [120, 256]]
[[95, 123], [202, 239], [432, 477], [623, 773]]
[[1, 57], [100, 830], [1170, 1653], [1732, 1796]]
[[1, 304], [513, 698]]
[[1, 42], [97, 300]]
[[1, 32], [297, 568]]
[[1, 236]]
[[58, 203], [556, 628]]
[[131, 374], [454, 468]]
[[1, 42], [115, 272], [597, 612]]
[[1, 76], [215, 824]]
[[1, 15], [141, 351]]
[[63, 223]]
[[1, 297], [720, 779]]
[[1, 147], [200, 377]]
[[1, 197], [248, 444]]
[[118, 158], [746, 762]]
[[1, 106], [309, 399]]
[[1, 429]]
[[1, 157], [224, 674]]
[[1, 125]]
[[1, 21], [111, 331]]
[[94, 479]]
[[1, 82]]
[[1, 171], [259, 292]]
[[1, 164], [238, 285]]
[[1, 383], [544, 693]]
[[1, 272], [407, 450]]
[[1, 118], [240, 372]]
[[102, 294], [340, 424], [465, 546]]
[[1, 53], [117, 234]]
[[1, 18], [471, 525], [598, 680], [824, 1901], [1983, 2169], [2281, 2358], [2430, 2653], [2692, 2724]]
[[1, 301], [344, 375], [413, 814]]
[[1, 45], [111, 331], [450, 481]]
[[1, 210], [329, 568], [620, 655], [696, 997], [1093, 1215]]
[[1, 259], [374, 442], [499, 515]]
[[1, 692]]
[[1, 322], [471, 495]]
[[1, 132], [189, 288]]
[[1, 251], [406, 468]]
[[1, 24], [93, 121]]
[[1, 128], [214, 496]]
[[1, 48], [173, 403]]
[[1, 26], [123, 157]]
[[1, 48], [198, 223]]
[[1, 108]]
[[63, 216], [316, 350]]
[[1, 19], [260, 449]]
[[180, 273]]
[[1, 144], [211, 332]]
[[1, 295], [406, 527]]
[[1, 120], [484, 537]]
[[1, 123], [164, 304], [342, 462], [504, 654], [1039, 1064]]
[[60, 160], [629, 642]]
[[1, 62], [259, 386]]
[[56, 175], [477, 500]]
[[1, 77], [130, 227]]
[[1, 62], [106, 125], [175, 469], [523, 1049]]
[[1, 67], [127, 303]]
[[57, 166]]
[[1, 192], [303, 448], [543, 566]]
[[73, 212]]
[[1, 260], [354, 374]]
[[1, 16], [241, 282]]
[[50, 252], [502, 554]]
[[1, 37], [126, 143]]
[[1, 112], [205, 223], [274, 333], [379, 413]]
[[1, 16], [431, 487], [530, 557]]
[[1, 32], [138, 366]]
[[164, 507]]
[[1, 81], [215, 571], [712, 826]]
[[1, 146], [422, 453]]
[[1, 219]]
[[42, 99]]
[[50, 204]]
[[1, 273], [544, 1532]]
[[1, 18], [218, 537], [660, 680], [815, 1034], [1136, 1203]]
[[1, 340], [395, 754]]
[[1, 156], [220, 344]]
[[1, 133], [193, 274]]
[[1, 59], [98, 236], [277, 397], [452, 478]]
[[1, 118], [159, 306], [516, 555]]
[[1, 95], [143, 259]]
[[1, 119]]
[[1, 440]]
[[1, 186], [235, 286], [595, 612]]
[[1, 85], [263, 333]]
[[1, 27], [137, 376], [487, 585]]
[[1, 269], [408, 533]]
[[1, 16], [75, 241]]
[[194, 247]]
[[1, 272]]
[[128, 193], [322, 572], [619, 649], [954, 1054]]
[[1, 380], [696, 944]]
[[1, 87], [179, 205]]
[[57, 173], [485, 499]]
[[1, 306], [375, 604], [648, 698], [815, 862], [916, 1042], [1088, 1224], [1274, 1386], [1454, 1585], [1628, 1652]]
[[1, 151]]
[[1, 141], [362, 608]]
[[1, 263], [479, 687]]
[[1, 89], [277, 437]]
[[1, 333], [414, 433], [485, 505]]
[[1, 138], [257, 292]]
[[1, 109], [161, 216]]
[[100, 121], [651, 695]]
[[1, 141], [205, 381]]
[[1, 377]]
[[1, 22]]
[[1, 181], [251, 302], [548, 596]]
[[1, 419], [489, 525]]
[[1, 388]]
[[1, 104], [283, 394]]
[[1, 249]]
[[1, 210], [415, 438]]
[[1, 561], [629, 680]]
[[138, 195], [388, 546], [585, 600]]
[[1, 619], [707, 746]]
[[1, 418], [787, 802]]
[[1, 236], [348, 1107]]
[[1, 601], [665, 731]]
[[188, 509]]
[[1, 154], [212, 256]]
[[1, 159], [214, 265]]
[[1, 184], [256, 270]]
[[1, 198], [269, 304], [355, 480]]
[[1, 139], [194, 218]]
[[1, 143], [199, 236]]
[[1, 207]]
[[1, 144], [199, 289]]
[[1, 24], [76, 178], [236, 277]]
[[1, 15], [64, 216]]
[[1, 63]]
[[1, 184], [294, 341], [382, 487], [617, 660]]
NA-NA
[[1, 309], [410, 485]]
[[70, 167]]
[[69, 167]]
[[1, 220], [274, 349], [432, 549], [633, 670], [719, 794], [1038, 1060]]
[[56, 238]]
[[63, 224], [610, 623]]
[[1, 434], [581, 1587]]
[[1, 480], [623, 1581]]
[[1, 34], [85, 298], [646, 660]]
[[1, 47], [121, 272]]
[[113, 295], [615, 689]]
[[1, 180]]
[[1, 38], [197, 641]]
[[1, 23], [189, 713]]
[[1, 31], [178, 701]]
[[1, 555], [630, 662]]
[[1, 83], [155, 177], [412, 463]]
[[1, 51], [127, 166]]
[[1, 83], [158, 179]]
[[1, 83], [155, 176], [413, 456]]
[[1, 42], [380, 491]]
[[1, 94]]
[[108, 326]]
[[1, 338], [420, 477]]
[[1, 124], [208, 308], [402, 480]]
[[1, 18], [152, 220]]
[[1, 73], [150, 193]]
[[1, 144], [217, 509]]
[[1, 293]]
[[1, 96], [317, 546], [708, 729]]
[[1, 153], [357, 522]]
[[1, 151], [213, 281]]
[[1, 108], [181, 373]]
[[1, 66], [147, 256]]
[[1, 205], [255, 291]]
[[1, 86], [159, 181], [418, 455]]
[[1, 221]]
[[102, 350]]
[[1, 193], [246, 432]]
[[1, 148], [198, 357]]
[[1, 208], [259, 302]]
[[1, 283], [353, 386], [435, 744]]
[[1, 35], [143, 310]]
[[1, 68], [171, 348]]
[[1, 88], [168, 321]]
[[1, 60], [143, 225]]
[[62, 359], [419, 506]]
[[1, 108], [171, 272]]
[[1, 131], [187, 327]]
[[1, 238]]
[[1, 20], [71, 196]]
[[1, 397], [465, 2085], [2141, 2719]]
[[1, 95], [222, 535]]
[[1, 568], [628, 668]]
[[1, 99], [1013, 1044]]
[[1, 552], [613, 655]]
[[1, 197], [301, 414]]
[[1, 269]]
[[1, 164]]
[[1, 84], [144, 373]]
[[1, 420], [792, 806]]
[[61, 267], [683, 698]]
[[1, 138]]
[[64, 160], [549, 564]]
[[1, 213]]
[[1, 194]]
[[1, 38], [138, 409], [536, 550]]
[[68, 156], [444, 459]]
[[1, 202]]
[[1, 18], [81, 228], [615, 640]]
[[1, 47], [189, 225]]
[[1, 191]]
[[1, 52], [118, 248]]
[[1, 53], [126, 374], [541, 564]]
[[59, 121], [443, 457]]
[[69, 170]]
[[62, 259], [543, 562]]
[[51, 244]]
[[1, 197], [417, 447]]
[[56, 177], [791, 810]]
[[69, 150]]
[[1, 52], [131, 350], [413, 706], [814, 874], [1029, 1044]]
[[1, 73]]
[[1, 108]]
[[62, 244], [387, 410], [611, 687]]
[[1, 24], [70, 252], [443, 576]]
[[1, 264]]
[[1, 156], [202, 244]]
[[1, 190]]
[[1, 161], [221, 252]]
[[1, 152], [211, 225]]
[[1, 264], [335, 348]]
[[1, 180], [247, 332]]
[[80, 336], [401, 484]]
[[1, 272]]
[[1, 69], [147, 262]]
[[1, 169], [250, 271]]
[[1, 336], [419, 544]]
[[1, 2236], [2308, 2332]]
[[1, 212]]
[[1, 91]]
[[1, 277]]
[[1, 302], [395, 450], [635, 671]]
[[91, 429]]
[[1, 218], [326, 477]]
[[1, 22], [69, 331], [438, 576]]
[[1, 323]]
[[1, 249], [316, 334]]
[[1, 126], [208, 254]]
[[357, 498], [890, 969]]
[[1, 162]]
[[1, 320], [388, 409], [461, 501]]
[[1, 268], [335, 359], [408, 444]]
[[1, 127], [214, 425]]
[[1, 192], [257, 271]]
[[1, 92], [179, 204], [282, 632]]
[[69, 261]]
NA-NA
[[1, 243]]
[[1, 439], [528, 567], [913, 980]]
[[1, 266], [340, 365]]
[[1, 91]]
[[1, 72], [163, 243]]
[[1, 94], [148, 608], [682, 707], [754, 767], [835, 880]]
[[1, 348]]
[[1, 26], [163, 221], [280, 454]]
[[1, 32], [156, 223], [281, 480]]
[[1, 291], [390, 481]]
[[1, 262], [359, 444]]
[[121, 350], [395, 436]]
[[1, 75], [154, 168]]
[[1, 55], [151, 208]]
[[1, 293]]
[[1, 27], [87, 351], [600, 617], [686, 732], [1095, 1131]]
[[1, 14], [145, 201], [273, 423]]
[[1, 97], [238, 259], [456, 790]]
[[1, 106]]
[[102, 432]]
[[1, 36], [104, 210]]
[[1, 286]]
[[1, 273]]
[[1, 177], [244, 304]]
[[1, 43], [98, 359], [458, 484]]
[[1, 201], [276, 336]]
[[1, 198], [254, 433]]
[[1, 340]]
[[1, 158], [215, 234]]
[[1, 129], [188, 231]]
[[1, 207]]
[[1, 246]]
[[1, 330]]
[[1, 155], [204, 243]]
[[1, 191]]
[[1, 223]]
[[1, 331]]
[[1, 269]]
[[1, 205], [291, 331]]
[[1, 186], [251, 1796], [1856, 2447]]
[[1, 39], [94, 355]]
[[1, 38], [96, 290]]
[[1, 111], [202, 432]]
[[1, 203], [299, 620]]
[[104, 164], [235, 345]]
[[1, 70], [161, 264]]
[[1, 208]]
[[1, 287]]
[[1, 149], [215, 268]]
[[1, 128]]
[[37, 92], [189, 238], [318, 558]]
[[1, 191], [272, 560], [663, 764]]
[[1, 146], [261, 591], [724, 829]]
[[1, 87], [151, 319]]
[[1, 37], [116, 442]]
[[60, 171]]
[[1, 42], [185, 198], [395, 849]]
[[1, 270], [335, 385]]
[[1, 164], [366, 571]]
[[1, 326], [397, 542], [985, 1014], [1051, 1082]]
[[1, 132]]
[[1, 169], [285, 594], [632, 901], [985, 1125]]
[[363, 555], [621, 933], [1008, 1116], [1209, 1262], [1308, 1506]]
[[1, 42], [98, 148], [303, 431]]
[[1, 53], [105, 157], [317, 431]]
[[1, 43], [97, 149], [316, 435]]
[[686, 771]]
[[1, 356]]
[[1, 22], [120, 513]]
[[1, 519], [680, 707]]
[[1, 43], [131, 318], [435, 453]]
[[1, 144], [214, 447]]
[[1, 61], [374, 475]]
[[105, 408]]
[[687, 751]]
[[311, 351], [621, 848]]
[[703, 795]]
[[1, 310], [447, 485]]
[[1, 261], [335, 368]]
[[1, 213], [312, 443]]
[[1, 166], [224, 372]]
[[1, 155], [211, 266]]
[[1, 176], [286, 339], [402, 427], [681, 724]]
[[1, 158], [275, 331], [650, 750]]
[[1, 29], [164, 196], [249, 617]]
[[1, 50], [114, 318]]
[[1, 70], [167, 510]]
[[1, 134], [214, 264]]
[[118, 190], [247, 407]]
[[1, 110], [185, 360]]
[[1, 44]]
[[1, 181], [246, 408]]
[[1, 263], [572, 728]]
[[1, 289]]
[[1, 211], [254, 270]]
[[1, 32], [126, 342]]
[[1, 246], [300, 402]]
[[1, 176], [227, 255]]
[[1, 192], [245, 305]]
[[1, 46], [184, 274], [328, 407]]
[[1, 75], [156, 229]]
[[1, 18], [118, 549]]
[[1, 273], [463, 478]]
[[1, 124], [186, 237]]
[[1, 27], [122, 264], [506, 519]]
[[1, 45], [250, 274]]
[[1, 20], [70, 332]]
[[1, 120]]
[[57, 212]]
[[1, 106], [151, 487]]
[[698, 788]]
[[1, 160]]
[[1, 68], [114, 366], [808, 822]]
[[1, 51], [130, 360], [492, 511]]
[[1, 253], [320, 352]]
[[706, 852]]
[[52, 209], [622, 655]]
[[1, 162]]
[[59, 158], [432, 458]]
[[1, 258], [446, 624]]
[[1, 290]]
[[1, 54], [104, 173]]
[[1, 24], [68, 208]]
[[1, 102]]
[[1, 162], [607, 807], [890, 1106], [1154, 1167], [1303, 1337], [1404, 1423], [1640, 1688]]
[[1, 237], [436, 639]]
[[1, 110]]
[[1, 145], [203, 284]]
[[1, 254], [306, 349]]
[[1, 141], [203, 325]]
[[1, 34], [203, 282]]
[[1, 163], [219, 339]]
[[1, 80], [133, 151]]
[[1, 63], [266, 389]]
[[1, 100], [167, 246]]
[[1, 126], [220, 238]]
[[1, 80], [171, 219]]
[[1, 182], [267, 490]]
[[1, 166], [268, 473]]
[[1, 109], [217, 351]]
[[1, 53], [157, 266], [320, 437]]
[[131, 342]]
[[1, 135], [188, 256]]
[[1, 141], [197, 290]]
[[1, 55], [106, 176]]
[[1, 274], [433, 478]]
[[1, 72], [166, 467]]
[[1, 146], [214, 258]]
[[1, 732], [877, 903], [962, 994], [1242, 1508]]
[[1, 103], [161, 447]]
[[1, 62], [266, 546]]
[[1, 258]]
[[1, 54], [148, 377]]
[[1, 151], [256, 362]]
[[1, 139]]
[[1, 288], [471, 543]]
[[1, 56], [135, 245], [284, 487], [571, 593], [649, 681], [730, 760], [818, 832], [915, 976]]
[[1, 47], [107, 161]]
[[1, 111], [188, 218]]
[[136, 185], [244, 350]]
NA-NA
[[1, 113], [208, 233]]
[[1, 52], [113, 325]]
[[1, 94], [157, 315]]
[[1, 18], [198, 347], [658, 719], [811, 858], [951, 999]]
[[1, 213], [291, 334]]
[[1, 116], [175, 484]]
[[1, 151], [208, 447]]
[[1, 150], [205, 520]]
[[1, 131], [189, 481]]
[[1, 134], [189, 502]]
[[1, 478], [597, 610], [671, 692]]
[[1, 240], [298, 368]]
[[1, 70], [153, 255]]
[[1, 19], [348, 767]]
[[1, 444], [913, 986]]
[[137, 223]]
[[1, 81], [270, 853], [947, 966]]
[[1, 131], [214, 308], [398, 734]]
[[1, 250], [301, 406], [804, 857], [965, 980]]
[[1, 268], [573, 800]]
[[1, 270], [576, 804]]
[[1, 104], [170, 506]]
[[1, 248], [380, 396]]
[[1, 217], [273, 321]]
[[57, 103]]
[[1, 162]]
[[1, 62], [305, 323]]
[[1, 16], [206, 530]]
[[1, 36], [320, 438], [696, 901]]
[[102, 209]]
[[1, 131], [289, 438]]
[[1, 261], [315, 365], [400, 439]]
[[1, 37], [84, 105], [161, 261], [346, 661]]
[[1, 49], [171, 454]]
[[1, 164], [399, 580]]
[[1, 565], [640, 777], [861, 996]]
[[1, 124], [202, 274], [375, 453]]
[[153, 177]]
[[1, 40], [120, 145], [220, 339]]
[[1, 65], [254, 369], [446, 498], [557, 650], [704, 764]]
[[1, 264], [345, 365]]
[[1, 133], [284, 361]]
[[1, 168]]
[[1, 35], [200, 356], [396, 710], [755, 909], [960, 995]]
[[79, 508]]
[[86, 366]]
[[1, 517]]
[[1, 272], [660, 683]]
[[1, 647], [735, 785]]
[[1, 623], [705, 782]]
[[1, 26], [135, 392]]
[[384, 427]]
[[1, 68]]
[[1, 69]]
[[1, 377], [442, 509]]
[[1, 22], [143, 418]]
[[1, 153], [194, 271]]
[[1, 254], [318, 345], [394, 452]]
[[1, 281]]
[[1, 118], [192, 257], [433, 908], [989, 1231]]
[[1, 1161], [1201, 1414], [1661, 1872], [2077, 3668], [3783, 3825]]
[[1, 58]]
[[1, 168], [620, 684], [763, 1055]]
[[1, 188], [251, 477]]
[[64, 170]]
[[1, 106]]
[[196, 537]]
[[64, 189], [557, 587]]
[[62, 167]]
[[1, 56], [147, 237], [273, 595]]
[[303, 552]]
[[1, 291]]
[[1, 159], [209, 253]]
[[269, 620]]
[[1, 61], [134, 205]]
[[1, 65], [144, 222]]
[[1, 473]]
[[69, 177], [1171, 1192]]
[[1, 409]]
[[1, 306], [373, 393]]
[[1, 31], [452, 501]]
[[82, 474]]
[[1, 131], [283, 360]]
[[1, 40], [265, 320], [435, 455]]
[[1, 23], [140, 451]]
[[1, 18], [67, 326], [768, 811]]
[[67, 326]]
[[1, 273], [359, 388]]
[[1, 60], [127, 475]]
[[1, 155], [211, 329]]
[[1, 97]]
[[1, 238], [327, 764]]
[[48, 169], [366, 667]]
[[49, 183], [763, 782]]
[[70, 198], [558, 601]]
[[1, 280], [591, 604]]
[[48, 145]]
[[1, 90], [148, 398]]
[[1, 231]]
[[1, 257]]
[[1, 225]]
[[1, 338], [416, 531], [818, 832], [1052, 1075]]
[[1, 160], [224, 656]]
[[1, 56], [235, 330]]
[[1, 234], [557, 794], [981, 1005], [1049, 2618], [2716, 2730], [2784, 2866], [3032, 3047]]
[[1, 253]]
[[186, 510]]
[[1, 83], [135, 200]]
[[1, 176], [502, 539]]
[[1, 49], [139, 380]]
[[1, 103], [188, 445]]
[[1, 73], [166, 554]]
[[1, 110], [166, 440]]
[[1, 111], [210, 379]]
[[1, 18], [138, 346]]
[[1, 421], [698, 1076]]
[[1, 350], [963, 1121]]
[[1, 21], [155, 356], [408, 1139], [1224, 1719]]
[[1, 25], [111, 304], [630, 804]]
[[1, 156]]
[[1, 398], [464, 481]]
[[1, 216], [418, 1055]]
[[1, 52], [482, 550], [600, 708], [820, 1126], [1192, 1302], [1376, 1409], [1474, 1531], [1594, 1915]]
[[1, 93], [184, 205]]
[[1, 101], [287, 713]]
[[94, 219]]
[[1, 37], [140, 590]]
[[1, 276]]
[[1, 282]]
[[1, 259]]
[[1, 115], [236, 423]]
[[1, 72], [168, 320]]
[[1, 381], [659, 926]]
[[1, 14], [141, 314], [459, 489]]
[[1, 25], [81, 206], [263, 335]]
[[1, 103], [181, 324]]
[[1, 64]]
[[1, 93], [194, 357]]
[[1, 21], [120, 233], [468, 499]]
[[1, 58], [175, 416]]
[[1, 142]]
[[1, 375]]
[[375, 400], [462, 498], [556, 590], [664, 679]]
[[1, 90], [222, 522]]
[[1, 20], [123, 459]]
[[1, 170], [321, 522]]
[[1, 417], [478, 954]]
[[58, 122], [347, 411]]
[[1, 146], [255, 277], [351, 447]]
[[1, 19], [349, 668]]
[[1, 131], [298, 438]]
[[1, 43], [155, 281]]
[[1, 621], [753, 773]]
[[1, 503], [610, 646], [708, 734]]
[[84, 132], [326, 409]]
[[1, 267], [324, 364]]
[[41, 54], [138, 210]]
[[1, 209]]
[[1, 59], [476, 489]]
[[59, 374]]
[[1, 80], [132, 279]]
[[1, 179], [671, 701]]
[[49, 318]]
[[1, 19], [54, 192], [492, 563]]
[[1, 36], [92, 204], [535, 570]]
[[1, 192]]
[[673, 749]]
[[1, 269], [333, 489]]
[[64, 533]]
[[58, 197]]
[[91, 522]]
[[80, 93], [245, 315], [410, 1189]]
[[1, 142], [307, 754]]
[[91, 206]]
[[66, 234], [518, 537], [584, 604]]
[[1, 402], [683, 903]]
[[186, 503]]
NA-NA
[[1, 101], [200, 324]]
[[1, 22], [104, 192], [398, 566], [854, 1198]]
NA-NA
[[1, 136], [478, 498]]
[[1, 299], [352, 449]]
[[1, 16], [134, 172], [439, 452]]
[[1, 181], [268, 282]]
[[1, 54], [234, 347]]
[[1, 94], [144, 492], [868, 906]]
[[1, 47], [128, 246]]
[[1, 414], [473, 916]]
[[178, 285]]
[[1, 88], [286, 493]]
[[1, 42], [131, 220]]
[[1, 48], [116, 221], [312, 326]]
[[1, 173], [231, 402]]
[[1, 43], [95, 108], [183, 233], [381, 1465]]
[[1, 100]]
[[1, 106]]
[[1, 37], [141, 323]]
[[1, 138], [204, 327]]
[[1, 979], [1036, 1074]]
[[1, 204], [299, 594]]
[[1, 201]]
[[1, 49], [141, 321], [563, 579]]
[[1, 123], [208, 383]]
[[1, 40], [82, 109], [366, 1442]]
[[135, 263]]
[[1, 280]]
[[1, 641], [742, 806], [841, 942], [1124, 1222], [1291, 1362], [1463, 1539], [1574, 2258], [2298, 2528], [2577, 2650], [2760, 2955], [3088, 3456], [3503, 3704]]
[[1, 238], [378, 448]]
[[134, 298], [399, 425]]
[[67, 185]]
[[49, 215]]
[[1, 188]]
[[49, 122]]
[[1, 22], [80, 454], [574, 606]]
[[1, 21], [200, 357]]
[[1, 54], [95, 126]]
[[1, 214]]
[[66, 109]]
[[1, 50], [91, 249], [581, 645]]
[[1, 208]]
[[1, 232]]
[[1, 257]]
[[1, 77], [153, 463]]
[[1, 200], [408, 683]]
[[1, 100], [283, 504]]
[[1, 35], [368, 827]]
[[1, 63], [115, 281]]
[[1, 125], [222, 466]]
[[1, 374], [463, 812], [945, 1017], [1069, 1082]]
[[1, 37], [415, 465]]
[[1, 44], [85, 104], [178, 213], [259, 1461]]
[[1, 139], [241, 410], [501, 688], [832, 929], [1043, 1168]]
[[1, 87], [144, 246]]
[[1, 14], [68, 262]]
[[66, 232], [539, 572]]
[[57, 224], [336, 382], [568, 582]]
[[1, 177], [473, 859]]
[[1, 229], [264, 481], [561, 665]]
[[1, 39], [237, 939]]
[[1, 14], [53, 203], [539, 594]]
[[1, 22], [61, 194]]
[[1, 18], [60, 724]]
[[1, 61], [496, 736]]
[[1, 405]]
[[1, 126], [164, 234]]
[[1, 205]]
[[1, 152]]
[[1, 98]]
[[1, 282], [586, 633]]
[[57, 209]]
[[1, 45], [117, 247]]
[[56, 167]]
[[1, 25], [65, 235]]
[[1, 232], [335, 377]]
[[1, 110], [179, 418]]
NA-NA
[[1, 52], [100, 221], [629, 645]]
[[1, 152]]
[[150, 164], [423, 453]]
[[92, 268]]
[[1, 81], [125, 269]]
[[1, 116], [155, 199], [674, 694]]
[[1, 45]]
[[1, 74], [148, 597]]
[[1, 122], [174, 426], [487, 511]]
[[52, 72], [397, 478]]
[[1, 30], [74, 153], [335, 349]]
[[1, 50], [184, 270], [361, 392], [488, 643]]
[[1, 65], [150, 356], [546, 562]]
[[1, 472]]
[[1, 303], [472, 583]]
[[59, 202], [555, 628]]
[[1, 32], [223, 452], [640, 1060]]
[[65, 201]]
[[1, 124], [368, 406]]
[[1, 52], [156, 169], [221, 639]]
[[63, 215]]
[[1, 18], [68, 144], [222, 331], [593, 611]]
[[1, 246], [629, 667]]
[[1, 141], [193, 1678]]
[[1, 285], [358, 390]]
[[1, 61], [134, 329]]
[[1, 381], [802, 853]]
[[59, 196], [418, 445]]
[[65, 186]]
[[1, 72], [155, 335]]
[[1, 81], [176, 460], [743, 910]]
[[1, 95]]
[[1, 85], [122, 159], [497, 723], [759, 773], [811, 1470]]
[[1, 227], [407, 421]]
[[1, 189], [247, 639], [674, 1751], [1800, 2407]]
[[54, 157]]
[[1, 276], [553, 569]]
[[1, 27], [344, 538]]
[[1, 127], [219, 464], [845, 872]]
[[1, 15], [122, 167]]
[[139, 353], [452, 504]]
[[1, 251]]
[[54, 187]]
[[1, 1604]]
[[52, 515], [1039, 1060]]
[[54, 241]]
[[1, 162]]
[[1, 892], [980, 1059], [1102, 1119], [1195, 2280]]
[[1, 109], [198, 417]]
[[1, 112], [301, 316]]
[[1, 397], [537, 559], [812, 829]]
[[1, 17], [111, 433]]
[[1, 91], [153, 329], [368, 505]]
[[78, 169], [253, 374]]
[[1, 111], [164, 326]]
[[1, 773], [933, 968]]
[[1, 377], [420, 900], [1014, 1039]]
[[1, 190], [277, 443], [600, 785]]
[[1, 231], [330, 462]]

,id,ProteinSeq,DBD_coords_merged,IDR_coords_merged,uniprotID,IDR_coords
0,sp|A0A087WUV0|ZN892_HUMAN Zinc finger protein ...,MEPEGRGSLFEDSDLLHAGNPKENDVTAVLLTPGSQELMIRDMAEA...,"[[221, 243], [249, 271], [277, 299], [305, 327...","[[1, 216], [498, 523]]",A0A087WUV0,"1-216,498-523"
1,sp|A0AVK6|E2F8_HUMAN Transcription factor E2F8...,MENEKENLFCEPHKRGLMKTPLKESTTANIVLAEIQPDFGPLTTPT...,"[[114, 182], [262, 347]]","[[1, 115], [337, 868]]",A0AVK6,"1-115,337-868"
2,sp|A0PJY2|FEZF1_HUMAN Fez family zinc finger p...,MDSSCHNATTKMLATAPARGNMMSTSKPLAFSIERIMARTPEPKAL...,"[[260, 282], [288, 310], [316, 338], [344, 366...","[[1, 220], [422, 476]]",A0PJY2,"1-220,422-476"
3,sp|A1A519|F170A_HUMAN Protein FAM170A OS=Homo ...,MKRRQKRKHLENEESQETAEKGGGMSKSQEDALQPGSTRVAKGWSQ...,"[[1, 330]]","[[1, 219], [269, 331]]",A1A519,"1-219,269-331"
4,sp|A1YPR0|ZBT7C_HUMAN Zinc finger and BTB doma...,MANDIDELIGIPFPNHSSEVLCSLNEQRHDGLLCDVLLVVQEQEYR...,"[[364, 386], [392, 414], [420, 442], [448, 469]]","[[128, 364], [471, 620]]",A1YPR0,"128-364,471-620"
...,...,...,...,...,...,...
1608,sp|Q9Y6Q9|NCOA3_HUMAN Nuclear receptor coactiv...,MSGLGENLDPLASDSRKRKLPCDTPGQGLTCSGEKRRREQESKYIE...,"[[31, 83]]","[[1, 40], [86, 108], [177, 193], [355, 1425]]",Q9Y6Q9,"1-40,86-108,177-193,355-1425"
1609,sp|Q9Y6R6|Z780B_HUMAN Zinc finger protein 780B...,MVHGSVTFRDVAIDFSQEEWECLQPDQRTLYRDVMLENYSHLISLG...,"[[165, 187], [193, 215], [221, 243], [249, 271...","[[64, 161], [809, 834]]",Q9Y6R6,"64-161,809-834"
1610,sp|Q9Y6X0|SETBP_HUMAN SET-binding protein OS=H...,MESRETLSSSRQRGGESDFLPVSSAKPPAAPGCAGEPLLSTPGPGK...,"[[583, 596], [1015, 1027], [1450, 1462]]","[[1, 1400], [1437, 1597]]",Q9Y6X0,"1-1400,1437-1597"
1611,sp|Q9Y6X8|ZHX2_HUMAN Zinc fingers and homeobox...,MASKRKSTTPCMVRTSQVVEQDVPEEVDRAKEKGIGTPQPDVAKDS...,"[[78, 101], [110, 133], [271, 317], [442, 496]...","[[1, 76], [150, 283], [334, 447], [589, 640], ...",Q9Y6X8,"1-76,150-283,334-447,589-640,695-838"
1612,sp|Q9Y6Y1|CMTA1_HUMAN Calmodulin-binding trans...,MWRAEGKWLPKTSRKSVSQSVFCGTSTYCVLNTVPPIEDDHGNSNS...,"[[69, 182]]","[[1, 55], [245, 863], [993, 1035], [1171, 1515...",Q9Y6Y1,"1-55,245-863,993-1035,1171-1515,1644-1674"

In [231]:
all_TFs_table_with_IDR = pd.merge(all_TFs_table, TF_seqs[["uniprotID", "IDR_coords"]], how='left')
#.to_csv("../soto_analysis/outputs/all_TFs_table_proteins_with_IDR.txt", sep = "\t")

In [232]:
all_TFs_table_with_IDR

,1,2,uniprotID,ENSG,ENST,DBD_coords,AD_coords,RD_coords,Bif_coords,length,IDR_coords
0,NaN,NaN,A0A087WUV0,NaN,ENST00000425953,"221-243,249-271,277-299,305-327,333-355,361-38...",NaN,NaN,NaN,1,"1-216,498-523"
1,NaN,NaN,A0AVK6,NaN,ENST00000250024,"114-182,262-347",NaN,NaN,NaN,1,"1-115,337-868"
2,NaN,NaN,A1YPR0,NaN,ENST00000535628,"364-386,392-414,420-442,448-469",NaN,NaN,NaN,1,"128-364,471-620"
3,NaN,NaN,A2RRD8,NaN,ENST00000391781,"161-183,189-211,217-239,245-267,273-295,301-32...",NaN,NaN,NaN,1,51-156
4,NaN,NaN,A2RU54,NaN,ENST00000339992,150-206,NaN,NaN,NaN,1,"1-158,224-274"
...,...,...,...,...,...,...,...,...,...,...,...
1585,NaN,NaN,Q9Y692,NaN,ENST00000294409,89-165,422-573,NaN,NaN,1,"1-90,183-258,348-574"
1586,NaN,NaN,Q9Y6Q3,NaN,ENST00000374227,"293-315,321-343,377-399,405-427,433-455,461-48...",NaN,NaN,NaN,1,"1-290,618-631"
1587,NaN,NaN,Q9Y6Q9,NaN,ENST00000371998,31-83,621-1424,NaN,NaN,1,"1-40,86-108,177-193,355-1425"
1588,NaN,NaN,Q9Y6X0,NaN,ENST00000649279,"583-596,1015-1027,1450-1462",NaN,NaN,NaN,1,"1-1400,1437-1597"
1589,NaN,NaN,Q9Y6Y1,NaN,ENST00000303635,69-182,"702-841,422-501",NaN,NaN,1,"1-55,245-863,993-1035,1171-1515,1644-1674"

# 2. Subtract AD intervals from IDR

In [217]:
# Need to get AD as bed 
all_TFs_table_with_IDR_AD = all_TFs_table_with_IDR[["uniprotID", "AD_coords"]]
all_TFs_table_with_IDR_AD["AD_coords"] = all_TFs_table_with_IDR_AD["AD_coords"].str.split(",")
all_TFs_table_with_IDR_AD = all_TFs_table_with_IDR_AD.explode("AD_coords")
all_TFs_table_with_IDR_AD = all_TFs_table_with_IDR_AD.dropna()
all_TFs_table_with_IDR_AD["start"] = all_TFs_table_with_IDR_AD["AD_coords"].str.split("-").str[0].astype(int)
all_TFs_table_with_IDR_AD["end"] = all_TFs_table_with_IDR_AD["AD_coords"].str.split("-").str[1].astype(int)
all_TFs_table_with_IDR_AD = all_TFs_table_with_IDR_AD.drop(columns= "AD_coords")
all_TFs_table_with_IDR_AD = all_TFs_table_with_IDR_AD[all_TFs_table_with_IDR_AD["start"] != "NA"]
all_TFs_table_with_IDR_AD

/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_81919/3605998393.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_TFs_table_with_IDR_AD["AD_coords"] = all_TFs_table_with_IDR_AD["AD_coords"].str.split(",")

     uniprotID  start   end
13      A6NJG6    142   315
27      A8MTJ6    369   420
33      A8MYZ6    382   491
45      O00570    125   391
48      O14627     32   131
...        ...    ...   ...
1582    Q9Y5R6    172   251
1585    Q9Y692    422   573
1587    Q9Y6Q9    621  1424
1589    Q9Y6Y1    702   841
1589    Q9Y6Y1    422   501

[597 rows x 3 columns]

In [218]:
# IDR as bed
all_TFs_table_with_IDR_IDR = all_TFs_table_with_IDR[["uniprotID", "IDR_coords"]]
all_TFs_table_with_IDR_IDR["IDR_coords"] = all_TFs_table_with_IDR_IDR["IDR_coords"].str.split(",")
all_TFs_table_with_IDR_IDR = all_TFs_table_with_IDR_IDR.explode("IDR_coords")
all_TFs_table_with_IDR_IDR = all_TFs_table_with_IDR_IDR.dropna()
all_TFs_table_with_IDR_IDR = all_TFs_table_with_IDR_IDR[all_TFs_table_with_IDR_IDR["IDR_coords"] != "NA-NA"]
all_TFs_table_with_IDR_IDR["start"] = all_TFs_table_with_IDR_IDR["IDR_coords"].str.split("-").str[0].astype(int)
all_TFs_table_with_IDR_IDR["end"] = all_TFs_table_with_IDR_IDR["IDR_coords"].str.split("-").str[1].astype(int)
all_TFs_table_with_IDR_IDR = all_TFs_table_with_IDR_IDR.drop(columns= "IDR_coords")
all_TFs_table_with_IDR_IDR

/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_81919/175853898.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_TFs_table_with_IDR_IDR["IDR_coords"] = all_TFs_table_with_IDR_IDR["IDR_coords"].str.split(",")

       uniprotID  start   end
0     A0A087WUV0      1   216
0     A0A087WUV0    498   523
1         A0AVK6      1   115
1         A0AVK6    337   868
2         A1YPR0    128   364
...          ...    ...   ...
1589      Q9Y6Y1      1    55
1589      Q9Y6Y1    245   863
1589      Q9Y6Y1    993  1035
1589      Q9Y6Y1   1171  1515
1589      Q9Y6Y1   1644  1674

[3447 rows x 3 columns]

In [219]:
all_TFs_table_with_IDR_AD.to_csv("../data/all_TFs_table_with_IDR_AD.bed", sep="\t", index=False, header=None)
all_TFs_table_with_IDR_IDR.to_csv("../data/all_TFs_table_with_IDR_IDR.bed", sep="\t", index=False, header=None)

In [ ]:
# Remove AD intervals from IDR
! bedtools subtract -a ../data/all_TFs_table_with_IDR_IDR.bed -b ../data/all_TFs_table_with_IDR_AD.bed > ../data/IDR_unique.bed

In [221]:
# Removed
IDR_AD_removed = pd.read_csv("../data/IDR_unique.bed", sep = "\t", header = None)
IDR_AD_removed.columns = ["uniprotID", "start", "end"]
IDR_AD_removed

       uniprotID  start   end
0     A0A087WUV0      1   216
1     A0A087WUV0    498   523
2         A0AVK6      1   115
3         A0AVK6    337   868
4         A1YPR0    128   364
...          ...    ...   ...
3730      Q9Y6Y1    501   702
3731      Q9Y6Y1    841   863
3732      Q9Y6Y1    993  1035
3733      Q9Y6Y1   1171  1515
3734      Q9Y6Y1   1644  1674

[3735 rows x 3 columns]

In [226]:
# Formatting output
IDR_AD_removed["non_AD_IDR_coords"] = IDR_AD_removed["start"].astype(str) + "-" + IDR_AD_removed["end"].astype(str)
IDR_AD_removed = IDR_AD_removed.drop(columns=["start", "end"])
IDR_AD_removed_grouped = IDR_AD_removed.groupby("uniprotID").agg(lambda x: ",".join(x))
IDR_AD_removed_grouped = IDR_AD_removed_grouped.reset_index()
IDR_AD_removed_grouped

       uniprotID                                  non_AD_IDR_coords
0     A0A087WUV0                                      1-216,498-523
1         A0AVK6                                      1-115,337-868
2         A0PJY2                                      1-220,422-476
3         A1A519                                      1-219,269-331
4         A1YPR0                                    128-364,471-620
...          ...                                                ...
1572      Q9Y6Q9              1-40,86-108,177-193,355-621,1424-1425
1573      Q9Y6R6                                     64-161,809-834
1574      Q9Y6X0                                   1-1400,1437-1597
1575      Q9Y6X8               1-76,150-283,334-447,589-640,695-838
1576      Q9Y6Y1  1-55,245-422,501-702,841-863,993-1035,1171-151...

[1577 rows x 2 columns]

In [228]:
# Merging back with the output table
all_TFs_table_with_IDR_minus_AD = pd.merge(all_TFs_table_with_IDR, IDR_AD_removed_grouped, how='left')

all_TFs_table_with_IDR_minus_AD

,1,2,uniprotID,ENSG,ENST,DBD_coords,AD_coords,RD_coords,Bif_coords,length,IDR_coords,non_AD_IDR_coords
0,NaN,NaN,A0A087WUV0,NaN,ENST00000425953,"221-243,249-271,277-299,305-327,333-355,361-38...",NaN,NaN,NaN,1,"1-216,498-523","1-216,498-523"
1,NaN,NaN,A0AVK6,NaN,ENST00000250024,"114-182,262-347",NaN,NaN,NaN,1,"1-115,337-868","1-115,337-868"
2,NaN,NaN,A1YPR0,NaN,ENST00000535628,"364-386,392-414,420-442,448-469",NaN,NaN,NaN,1,"128-364,471-620","128-364,471-620"
3,NaN,NaN,A2RRD8,NaN,ENST00000391781,"161-183,189-211,217-239,245-267,273-295,301-32...",NaN,NaN,NaN,1,51-156,51-156
4,NaN,NaN,A2RU54,NaN,ENST00000339992,150-206,NaN,NaN,NaN,1,"1-158,224-274","1-158,224-274"
...,...,...,...,...,...,...,...,...,...,...,...,...
1585,NaN,NaN,Q9Y692,NaN,ENST00000294409,89-165,422-573,NaN,NaN,1,"1-90,183-258,348-574","1-90,183-258,348-422,573-574"
1586,NaN,NaN,Q9Y6Q3,NaN,ENST00000374227,"293-315,321-343,377-399,405-427,433-455,461-48...",NaN,NaN,NaN,1,"1-290,618-631","1-290,618-631"
1587,NaN,NaN,Q9Y6Q9,NaN,ENST00000371998,31-83,621-1424,NaN,NaN,1,"1-40,86-108,177-193,355-1425","1-40,86-108,177-193,355-621,1424-1425"
1588,NaN,NaN,Q9Y6X0,NaN,ENST00000649279,"583-596,1015-1027,1450-1462",NaN,NaN,NaN,1,"1-1400,1437-1597","1-1400,1437-1597"
1589,NaN,NaN,Q9Y6Y1,NaN,ENST00000303635,69-182,"702-841,422-501",NaN,NaN,1,"1-55,245-863,993-1035,1171-1515,1644-1674","1-55,245-422,501-702,841-863,993-1035,1171-151..."

In [230]:
# Inspecting rows which changed
all_TFs_table_with_IDR_minus_AD[all_TFs_table_with_IDR_minus_AD["IDR_coords"] != all_TFs_table_with_IDR_minus_AD["non_AD_IDR_coords"]].head(10)

,1,2,uniprotID,ENSG,ENST,DBD_coords,AD_coords,RD_coords,Bif_coords,length,IDR_coords,non_AD_IDR_coords
13,NaN,NaN,A6NJG6,NaN,ENST00000334384,79-135,142-315,NaN,NaN,1,"1-83,137-208,266-316","1-83,137-142,315-316"
27,NaN,NaN,A8MTJ6,NaN,ENST00000428390,145-234,369-420,NaN,NaN,1,"1-133,234-421","1-133,234-369,420-421"
33,NaN,NaN,A8MYZ6,NaN,ENST00000641094,89-178,382-491,NaN,NaN,1,"1-86,159-493","1-86,159-382,491-493"
45,NaN,NaN,O00570,NaN,ENST00000330949,51-119,125-391,NaN,NaN,1,"1-57,128-392","1-57,391-392"
48,NaN,NaN,O14627,NaN,ENST00000373514,174-230,32-131,NaN,NaN,1,"1-160,237-285","1-32,131-160,237-285"
50,NaN,NaN,O14813,NaN,ENST00000298231,91-147,2-81,NaN,NaN,1,"1-86,150-285","1-2,81-86,150-285"
57,NaN,NaN,O15353,NaN,ENST00000226247,271-361,"482-601,152-231",NaN,NaN,1,"1-272,372-649","1-152,231-272,372-482,601-649"
58,NaN,NaN,O15370,NaN,ENST00000342665,40-108,232-315,NaN,NaN,1,"1-39,107-316","1-39,107-232,315-316"
59,NaN,NaN,O15391,NaN,ENST00000429584,"254-278,283-305,311-335,341-365",2-102,NaN,NaN,1,1-253,"1-2,102-253"
64,NaN,NaN,O43186,NaN,ENST00000221996,40-96,"126-174,192-291",NaN,NaN,1,"1-42,97-300","1-42,97-126,174-192,291-300"

In [233]:
# Drop IDR_coords
all_TFs_table_with_IDR_minus_AD = all_TFs_table_with_IDR_minus_AD.drop(columns="IDR_coords")
all_TFs_table_with_IDR_minus_AD

,1,2,uniprotID,ENSG,ENST,DBD_coords,AD_coords,RD_coords,Bif_coords,length,non_AD_IDR_coords
0,NaN,NaN,A0A087WUV0,NaN,ENST00000425953,"221-243,249-271,277-299,305-327,333-355,361-38...",NaN,NaN,NaN,1,"1-216,498-523"
1,NaN,NaN,A0AVK6,NaN,ENST00000250024,"114-182,262-347",NaN,NaN,NaN,1,"1-115,337-868"
2,NaN,NaN,A1YPR0,NaN,ENST00000535628,"364-386,392-414,420-442,448-469",NaN,NaN,NaN,1,"128-364,471-620"
3,NaN,NaN,A2RRD8,NaN,ENST00000391781,"161-183,189-211,217-239,245-267,273-295,301-32...",NaN,NaN,NaN,1,51-156
4,NaN,NaN,A2RU54,NaN,ENST00000339992,150-206,NaN,NaN,NaN,1,"1-158,224-274"
...,...,...,...,...,...,...,...,...,...,...,...
1585,NaN,NaN,Q9Y692,NaN,ENST00000294409,89-165,422-573,NaN,NaN,1,"1-90,183-258,348-422,573-574"
1586,NaN,NaN,Q9Y6Q3,NaN,ENST00000374227,"293-315,321-343,377-399,405-427,433-455,461-48...",NaN,NaN,NaN,1,"1-290,618-631"
1587,NaN,NaN,Q9Y6Q9,NaN,ENST00000371998,31-83,621-1424,NaN,NaN,1,"1-40,86-108,177-193,355-621,1424-1425"
1588,NaN,NaN,Q9Y6X0,NaN,ENST00000649279,"583-596,1015-1027,1450-1462",NaN,NaN,NaN,1,"1-1400,1437-1597"
1589,NaN,NaN,Q9Y6Y1,NaN,ENST00000303635,69-182,"702-841,422-501",NaN,NaN,1,"1-55,245-422,501-702,841-863,993-1035,1171-151..."

In [234]:
all_TFs_table_with_IDR_minus_AD.to_csv("../data/all_TFs_table_proteins_with_IDR.txt")